/**
 * Brand → primary web domain. Logos are fetched at runtime from a logo CDN by
 * domain (never bundled into the repo), so no trademarked image files are
 * stored here. Anything without a mapping — or whose logo fails to load — falls
 * back to a neutral monogram.
 */
const DOMAINS: Record<string, string> = {
  // Estée Lauder Companies
  "estee-lauder": "esteelauder.com",
  clinique: "clinique.com",
  "mac-cosmetics": "maccosmetics.com",
  "bobbi-brown": "bobbibrowncosmetics.com",
  aveda: "aveda.com",
  "la-mer": "cremedelamer.com",
  "jo-malone-london": "jomalone.com",
  "tom-ford-beauty": "tomford.com",
  origins: "origins.com",
  smashbox: "smashbox.com",
  "too-faced": "toofaced.com",
  drjart: "drjart.com",
  "lab-series": "labseries.com",
  "le-labo": "lelabofragrances.com",
  "kilian-paris": "bykilian.com",
  "frederic-malle": "fredericmalle.com",
  "bumble-and-bumble": "bumbleandbumble.com",
  // Coty
  coty: "coty.com",
  "rimmel-london": "rimmellondon.com",
  bourjois: "bourjois.com",
  "sally-hansen": "sallyhansen.com",
  "max-factor": "maxfactor.com",
  covergirl: "covergirl.com",
  manhattan: "manhattan-cosmetics.com",
  "miss-sporty": "miss-sporty.com",
  "kylie-cosmetics": "kyliecosmetics.com",
  "kylie-skin": "kylieskin.com",
  younique: "youniqueproducts.com",
  lancaster: "lancaster-beauty.com",
  adidas: "adidas.com",
  "bruno-banani": "bruno-banani.com",
  mexx: "mexx.com",
  nautica: "nautica.com",
  "calvin-klein": "calvinklein.com",
  "hugo-boss": "hugoboss.com",
  "gucci-beauty": "gucci.com",
  "burberry-beauty": "burberry.com",
  "marc-jacobs-fragrances": "marcjacobs.com",
  chloe: "chloe.com",
  davidoff: "davidoff.com",
  "tiffany-co": "tiffany.com",
  "vera-wang": "verawang.com",
  "roberto-cavalli": "robertocavalli.com",
  "jil-sander": "jilsander.com",
  joop: "joop.com",
  lacoste: "lacoste.com",
  escada: "escada.com",
  chopard: "chopard.com",
  cerruti: "cerruti.com",
  "bottega-veneta": "bottegaveneta.com",
  // L'Oréal Group
  loreal: "loreal.com",
  "loreal-paris": "lorealparis.com",
  maybelline: "maybelline.com",
  garnier: "garnier.com",
  "nyx-professional-makeup": "nyxcosmetics.com",
  essie: "essie.com",
  mixa: "mixa.com",
  "3ce": "stylenanda.com",
  "la-roche-posay": "laroche-posay.com",
  cerave: "cerave.com",
  vichy: "vichy.com",
  skinceuticals: "skinceuticals.com",
  "skinbetter-science": "skinbetter.com",
  lancome: "lancome.com",
  kiehls: "kiehls.com",
  "ysl-beauty": "yslbeauty.com",
  "giorgio-armani-beauty": "armanibeauty.com",
  "prada-beauty": "pradabeauty.com",
  "valentino-beauty": "valentino-beauty.com",
  biotherm: "biotherm.com",
  "urban-decay": "urbandecay.com",
  mugler: "mugler.com",
  azzaro: "azzaro.com",
  "viktor-rolf": "viktor-rolf.com",
  "ralph-lauren-fragrances": "ralphlauren.com",
  cacharel: "cacharel.com",
  diesel: "diesel.com",
  "helena-rubinstein": "helenarubinstein.com",
  "it-cosmetics": "itcosmetics.com",
  "shu-uemura": "shuuemura.com",
  aesop: "aesop.com",
  "house-of-creed": "creedboutique.com",
  "loreal-professionnel": "lorealprofessionnel.com",
  kerastase: "kerastase.com",
  redken: "redken.com",
  matrix: "matrix.com",
  pureology: "pureology.com",
  mizani: "mizani.com",
  "color-wow": "colorwowhair.com",
  // LVMH
  dior: "dior.com",
  guerlain: "guerlain.com",
  "givenchy-beauty": "givenchybeauty.com",
  "kenzo-parfums": "kenzoparfums.com",
  "loewe-perfumes": "loewe.com",
  "acqua-di-parma": "acquadiparma.com",
  "maison-francis-kurkdjian": "franciskurkdjian.com",
  fresh: "fresh.com",
  "benefit-cosmetics": "benefitcosmetics.com",
  "make-up-for-ever": "makeupforever.com",
  "fenty-beauty": "fentybeauty.com",
  "fenty-skin": "fentyskin.com",
  // Chanel
  chanel: "chanel.com",
  "chanel-beauty": "chanel.com",
  // Independent
  nivea: "nivea.com",
  eucerin: "eucerin.com",
  "the-ordinary": "theordinary.com",
  niod: "niod.com",
  nars: "narscosmetics.com",
  shiseido: "shiseido.com",
  "sk-ii": "sk-ii.com",
  "charlotte-tilbury": "charlottetilbury.com",
  "drunk-elephant": "drunkelephant.com",
  "paulas-choice": "paulaschoice.com",
  clarins: "clarins.com",
  "sephora-collection": "sephora.com",
};

export function getBrandDomain(slug: string): string | undefined {
  return DOMAINS[slug];
}

/** Ordered logo sources for a domain: real logo first, favicon fallback. */
export function logoSources(domain: string): string[] {
  return [
    `https://logo.clearbit.com/${domain}?size=128`,
    `https://www.google.com/s2/favicons?domain=${domain}&sz=128`,
  ];
}
