import gaps from "./locale-message-gaps.json";

/**
 * English-only brand-detail keys, per locale.
 *
 * A catalog holding a question but not its answer would otherwise render the
 * localized question above the English fallback, which is how mixed-language
 * FAQs reached production. The brand page checks both halves through
 * `hasReviewedBrandDetailKey` before rendering either.
 *
 * Per-locale rather than one shared list, because locales are translated at
 * different rates: Turkish now carries all 30 keys the other catalogs still
 * lack, and a single set could not express that without hiding Turkish content
 * that exists.
 *
 * Generated by `scripts/build-locale-message-gaps.mjs` and asserted against the
 * catalogs by the quality suite, so it cannot drift when a key is added or a
 * locale is translated.
 */
export const BRAND_DETAIL_GAPS: Record<string, readonly string[]> = gaps;

export function hasReviewedBrandDetailKey(locale: string, slug: string, key: string) {
  if (locale === "en") return true;
  return !BRAND_DETAIL_GAPS[locale]?.includes(`${slug}.${key}`);
}
