export type PhotoSubmissionCopy = {
  title: string;
  description: string;
  open: string;
  received: string;
  reply: string;
  missingPhoto: string;
  tooMany: string;
  choose: string;
  selected: string;
  noneSelected: string;
  code: string;
  problem: string;
  email: string;
  emailHelp: string;
  permission: string;
  consent: string;
  sendError: string;
  sending: string;
  send: string;
  help: string;
};

const KEYS = ["title","description","open","received","reply","missingPhoto","tooMany","choose","selected","noneSelected","code","problem","email","emailHelp","permission","consent","sendError","sending","send","help"] as const;
const RAW: Record<string, readonly string[]> = {
  "en": [
    "Can’t find or read the BRANDNAME code?",
    "Send clear photos of the base, label or box. We’ll review them and improve our examples.",
    "Send code photos",
    "Photo received",
    "We’ll review the code and reply to EMAILADDRESS.",
    "Choose at least one JPEG, PNG or WebP photo before sending.",
    "You can send up to 3 photos in one submission.",
    "Take or choose photos",
    "photos selected",
    "No photo selected.",
    "Visible code (optional)",
    "What went wrong? (optional)",
    "Email for our reply",
    "Used only to reply about this submission.",
    "Permission required.",
    "I confirm these are my photos and allow Cosmetics Batch to store the photos and my email, contact me about this submission, and use verified photo portions to improve its public guides. Personal details should not be visible.",
    "The photos could not be sent. Please try smaller JPEG, PNG or WebP images.",
    "Sending…",
    "Send for review",
    "Choose up to 3 JPEG, PNG or WebP images from your camera or gallery. Each image is resized and re-encoded before upload to remove embedded location metadata. Maximum: 5 MB per processed image. Avoid including faces or other personal details."
  ],
  "es": [
    "¿No puedes encontrar o leer el código BRANDNAME?",
    "Envía fotos claras de la base, la etiqueta o la caja. Las revisaremos y mejoraremos nuestros ejemplos.",
    "Enviar fotos de código",
    "Foto recibida",
    "Revisaremos el código y responderemos a EMAILADDRESS.",
    "Elija al menos una foto JPEG, PNG o WebP antes de enviarla.",
    "Puedes enviar hasta 3 fotos en un solo envío.",
    "Toma o elige fotos",
    "fotos seleccionadas",
    "Ninguna foto seleccionada.",
    "Código visible (opcional)",
    "¿Qué salió mal? (opcional)",
    "Correo electrónico para nuestra respuesta",
    "Se utiliza únicamente para responder sobre este envío.",
    "Se requiere permiso.",
    "Confirmo que estas son mis fotos y permito que Cosmetics Batch almacene las fotos y mi correo electrónico, me contacte sobre este envío y utilice partes de fotos verificadas para mejorar sus guías públicas. Los datos personales no deben ser visibles.",
    "Las fotos no se pudieron enviar. Pruebe con imágenes JPEG, PNG o WebP más pequeñas.",
    "Enviando…",
    "Enviar para revisión",
    "Elija hasta 3 imágenes JPEG, PNG o WebP de su cámara o galería. Cada imagen cambia de tamaño y se vuelve a codificar antes de cargarla para eliminar los metadatos de ubicación incrustados. Máximo: 5 MB por imagen procesada. Evite incluir rostros u otros datos personales."
  ],
  "fr": [
    "Vous ne trouvez pas ou ne lisez pas le code BRANDNAME ?",
    "Envoyez des photos claires de la base, de l'étiquette ou de la boîte. Nous les examinerons et améliorerons nos exemples.",
    "Envoyer des photos de codes",
    "Photo reçue",
    "Nous examinerons le code et répondrons à EMAILADDRESS.",
    "Choisissez au moins une photo JPEG, PNG ou WebP avant de l'envoyer.",
    "Vous pouvez envoyer jusqu'à 3 photos en une seule soumission.",
    "Prendre ou choisir des photos",
    "photos sélectionnées",
    "Aucune photo sélectionnée.",
    "Code visible (facultatif)",
    "Qu'est-ce qui n'a pas fonctionné ? (facultatif)",
    "Email pour notre réponse",
    "Utilisé uniquement pour répondre à cette soumission.",
    "Autorisation requise.",
    "Je confirme qu'il s'agit de mes photos et j'autorise Cosmetics Batch à stocker les photos et mon e-mail, à me contacter au sujet de cette soumission et à utiliser des parties de photos vérifiées pour améliorer ses guides publics. Les données personnelles ne doivent pas être visibles.",
    "Les photos n'ont pas pu être envoyées. Veuillez essayer des images JPEG, PNG ou WebP plus petites.",
    "Envoi…",
    "Envoyer pour examen",
    "Choisissez jusqu'à 3 images JPEG, PNG ou WebP depuis votre appareil photo ou votre galerie. Chaque image est redimensionnée et réencodée avant le téléchargement pour supprimer les métadonnées de localisation intégrées. Maximum : 5 Mo par image traitée. Évitez d'inclure des visages ou d'autres détails personnels."
  ],
  "de": [
    "Sie können den BRANDNAME-Code nicht finden oder lesen?",
    "Senden Sie klare Fotos der Basis, des Etiketts oder der Box. Wir werden sie überprüfen und unsere Beispiele verbessern.",
    "Senden Sie Codefotos",
    "Foto erhalten",
    "Wir überprüfen den Code und antworten auf EMAILADDRESS.",
    "Wählen Sie vor dem Senden mindestens ein JPEG-, PNG- oder WebP-Foto aus.",
    "Sie können bis zu 3 Fotos in einer Einreichung senden.",
    "Machen Sie Fotos oder wählen Sie sie aus",
    "Fotos ausgewählt",
    "Kein Foto ausgewählt.",
    "Sichtbarer Code (optional)",
    "Was ist schief gelaufen? (optional)",
    "E-Mail für unsere Antwort",
    "Wird nur verwendet, um auf diesen Beitrag zu antworten.",
    "Erlaubnis erforderlich.",
    "Ich bestätige, dass es sich hierbei um meine Fotos handelt und erlaube Cosmetics Batch, die Fotos und meine E-Mail-Adresse zu speichern, mich bezüglich dieser Einreichung zu kontaktieren und verifizierte Fototeile zur Verbesserung seiner öffentlichen Leitfäden zu verwenden. Persönliche Daten sollten nicht sichtbar sein.",
    "Die Fotos konnten nicht gesendet werden. Bitte versuchen Sie es mit kleineren JPEG-, PNG- oder WebP-Bildern.",
    "Senden…",
    "Zur Überprüfung senden",
    "Wählen Sie bis zu 3 JPEG-, PNG- oder WebP-Bilder aus Ihrer Kamera oder Galerie. Jedes Bild wird vor dem Hochladen in der Größe geändert und neu codiert, um eingebettete Standortmetadaten zu entfernen. Maximal: 5 MB pro verarbeitetem Bild. Vermeiden Sie die Angabe von Gesichtern oder anderen persönlichen Daten."
  ],
  "pt": [
    "Não consegue encontrar ou ler o código BRANDNAME?",
    "Envie fotos nítidas da base, da etiqueta ou da caixa. Vamos analisá-las e melhorar os nossos exemplos.",
    "Envie fotos de código",
    "Foto recebida",
    "Revisaremos o código e responderemos a EMAILADDRESS.",
    "Escolha pelo menos uma foto JPEG, PNG ou WebP antes de enviar.",
    "Você pode enviar até 3 fotos em um envio.",
    "Tire ou escolha fotos",
    "fotos selecionadas",
    "Nenhuma foto selecionada.",
    "Código visível (opcional)",
    "O que deu errado? (opcional)",
    "Email para nossa resposta",
    "Usado apenas para responder sobre este envio.",
    "É necessária permissão.",
    "Confirmo que estas são minhas fotos e permito que a Cosmetics Batch armazene as fotos e meu e-mail, entre em contato comigo sobre este envio e use partes de fotos verificadas para melhorar seus guias públicos. Os dados pessoais não devem estar visíveis.",
    "Não foi possível enviar as fotos. Tente imagens JPEG, PNG ou WebP menores.",
    "Enviando…",
    "Enviar para revisão",
    "Escolha até 3 imagens JPEG, PNG ou WebP da sua câmera ou galeria. Cada imagem é redimensionada e recodificada antes do upload para remover metadados de localização incorporados. Máximo: 5 MB por imagem processada. Evite incluir rostos ou outros dados pessoais."
  ],
  "ru": [
    "Не можете найти или прочитать код BRANDNAME?",
    "Отправьте четкие фотографии основания, этикетки или коробки. Мы их рассмотрим и улучшим наши примеры.",
    "Отправить фотографии кода",
    "Фото получено",
    "Мы проверим код и ответим на адрес EMAILADDRESS.",
    "Перед отправкой выберите хотя бы одну фотографию в формате JPEG, PNG или WebP.",
    "В одной заявке можно отправить до 3 фотографий.",
    "Сделайте или выберите фотографии",
    "фотографии выбраны",
    "Фотография не выбрана.",
    "Видимый код (необязательно)",
    "Что пошло не так? (необязательно)",
    "Электронная почта для нашего ответа",
    "Используется только для ответа на это сообщение.",
    "Требуется разрешение.",
    "Я подтверждаю, что это мои фотографии, и разрешаю Cosmetics Batch хранить фотографии и мою электронную почту, связываться со мной по поводу этой отправки и использовать проверенные части фотографий для улучшения своих общедоступных руководств. Личные данные не должны быть видны.",
    "Фотографии не удалось отправить. Попробуйте использовать изображения меньшего размера в формате JPEG, PNG или WebP.",
    "Отправка…",
    "Отправить на рассмотрение",
    "Выберите до трех изображений в формате JPEG, PNG или WebP из вашей камеры или галереи. Перед загрузкой размер каждого изображения изменяется и перекодируется, чтобы удалить встроенные метаданные о местоположении. Максимум: 5 МБ на каждое обработанное изображение. Избегайте включения лиц или других личных данных."
  ],
  "ar": [
    "ألا يمكنك العثور على رمز BRANDNAME أو قراءته؟",
    "أرسل صورًا واضحة للقاعدة أو الملصق أو الصندوق. سنقوم بمراجعتها وتحسين الأمثلة لدينا.",
    "إرسال صور الرمز",
    "تم استلام الصورة",
    "سنراجع الرمز ونرد على EMAILADDRESS.",
    "اختر صورة واحدة على الأقل بتنسيق JPEG أو PNG أو WebP قبل الإرسال.",
    "يمكنك إرسال ما يصل إلى 3 صور في إرسال واحد.",
    "التقاط أو اختيار الصور",
    "الصور المختارة",
    "لم يتم تحديد أي صورة.",
    "الكود المرئي (اختياري)",
    "ما الخطأ الذي حدث؟ (اختياري)",
    "البريد الإلكتروني لردنا",
    "تستخدم فقط للرد على هذا الإرسال.",
    "الإذن مطلوب.",
    "أؤكد أن هذه هي صوري وأسمح لـ Cosmetics Batch بتخزين الصور والبريد الإلكتروني الخاص بي، والاتصال بي بشأن هذا الإرسال، واستخدام أجزاء الصور التي تم التحقق منها لتحسين الأدلة العامة الخاصة بها. يجب ألا تكون التفاصيل الشخصية مرئية.",
    "لا يمكن إرسال الصور. الرجاء تجربة صور JPEG أو PNG أو WebP بحجم أصغر.",
    "جارٍ الإرسال...",
    "إرسال للمراجعة",
    "اختر ما يصل إلى 3 صور JPEG أو PNG أو WebP من الكاميرا أو المعرض. يتم تغيير حجم كل صورة وإعادة تشفيرها قبل التحميل لإزالة البيانات التعريفية للموقع المضمنة. الحد الأقصى: 5 ميجابايت لكل صورة تمت معالجتها. تجنب تضمين الوجوه أو التفاصيل الشخصية الأخرى."
  ],
  "zh": [
    "找不到或无法读取 BRANDNAME 代码？",
    "发送底座、标签或盒子的清晰照片。我们将审查它们并改进我们的示例。",
    "发送代码照片",
    "收到照片",
    "我们将审核代码并回复 EMAILADDRESS。",
    "发送前至少选择一张 JPEG、PNG 或 WebP 照片。",
    "您一次提交最多可以发送 3 张照片。",
    "拍摄或选择照片",
    "已选择照片",
    "未选择照片。",
    "可见代码（可选）",
    "出了什么问题？ （可选）",
    "我们回复的电子邮件",
    "仅用于回复此提交。",
    "需要许可。",
    "我确认这些是我的照片，并允许 Cosmetics Batch 存储这些照片和我的电子邮件，就此次提交与我联系，并使用经过验证的照片部分来改进其公共指南。个人详细信息不应可见。",
    "照片无法发送。请尝试较小的 JPEG、PNG 或 WebP 图像。",
    "正在发送...",
    "发送以供审核",
    "从相机或图库中选择最多 3 张 JPEG、PNG 或 WebP 图像。每个图像在上传之前都会调整大小并重新编码，以删除嵌入的位置元数据。最大值：每个已处理图像 5 MB。避免包含面孔或其他个人详细信息。"
  ],
  "tr": [
    "BRANDNAME kodunu bulamıyor veya okuyamıyor musunuz?",
    "Tabanın, etiketin veya kutunun net fotoğraflarını gönderin. Bunları inceleyip örneklerimizi geliştireceğiz.",
    "Kod fotoğraflarını gönder",
    "Fotoğraf alındı",
    "Kodu inceleyip EMAILADDRESS'e yanıt vereceğiz.",
    "Göndermeden önce en az bir JPEG, PNG veya WebP fotoğrafı seçin.",
    "Bir gönderide en fazla 3 fotoğraf gönderebilirsiniz.",
    "Fotoğraf çekin veya seçin",
    "seçilen fotoğraflar",
    "Fotoğraf seçilmedi.",
    "Görünür kod (isteğe bağlı)",
    "Ne yanlış gitti? (isteğe bağlı)",
    "Cevabımız için e-posta",
    "Yalnızca bu gönderime yanıt vermek için kullanılır.",
    "İzin gerekli.",
    "Bunların benim fotoğraflarım olduğunu onaylıyorum ve Cosmetics Batch'in fotoğrafları ve e-postamı saklamasına, bu gönderiyle ilgili olarak benimle iletişime geçmesine ve genel kılavuzlarını geliştirmek için doğrulanmış fotoğraf bölümlerini kullanmasına izin veriyorum. Kişisel ayrıntılar görünmemelidir.",
    "Fotoğraflar gönderilemedi. Lütfen daha küçük JPEG, PNG veya WebP görsellerini deneyin.",
    "Gönderiliyor…",
    "İnceleme için gönder",
    "Kameranızdan veya galerinizden en fazla 3 JPEG, PNG veya WebP görüntüsü seçin. Gömülü konum meta verilerini kaldırmak için her resim yüklemeden önce yeniden boyutlandırılır ve yeniden kodlanır. Maksimum: İşlenen görüntü başına 5 MB. Yüzleri veya diğer kişisel ayrıntıları eklemekten kaçının."
  ],
  "it": [
    "Non riesci a trovare o leggere il codice BRANDNAME?",
    "Invia foto nitide della base, dell'etichetta o della confezione. Le esamineremo per migliorare i nostri esempi.",
    "Invia foto del codice",
    "Foto ricevuta",
    "Esamineremo il codice e risponderemo a EMAILADDRESS.",
    "Scegli almeno una foto JPEG, PNG o WebP prima dell'invio.",
    "Puoi inviare fino a 3 foto in un unico invio.",
    "Scatta o scegli foto",
    "foto selezionate",
    "Nessuna foto selezionata.",
    "Codice visibile (facoltativo)",
    "Cosa è andato storto? (facoltativo)",
    "E-mail per la nostra risposta",
    "Utilizzato solo per rispondere a questo invio.",
    "Permesso richiesto.",
    "Confermo che queste sono le mie foto e consento a Cosmetics Batch di archiviare le foto e la mia email, di contattarmi in merito a questo invio e di utilizzare porzioni di foto verificate per migliorare le sue guide pubbliche. I dati personali non dovrebbero essere visibili.",
    "Non è stato possibile inviare le foto. Prova immagini JPEG, PNG o WebP più piccole.",
    "Invio…",
    "Invia per la revisione",
    "Scegli fino a 3 immagini JPEG, PNG o WebP dalla tua fotocamera o galleria. Ogni immagine viene ridimensionata e ricodificata prima del caricamento per rimuovere i metadati di posizione incorporati. Massimo: 5 MB per immagine elaborata. Evita di includere volti o altri dettagli personali."
  ],
  "nl": [
    "Kunt u de BRANDNAME-code niet vinden of lezen?",
    "Stuur duidelijke foto's van de basis, het label of de doos. We zullen ze beoordelen en onze voorbeelden verbeteren.",
    "Codefoto's verzenden",
    "Foto ontvangen",
    "We zullen de code beoordelen en antwoorden op EMAILADDRESS.",
    "Kies ten minste één JPEG-, PNG- of WebP-foto voordat u deze verzendt.",
    "U kunt maximaal 3 foto's in één inzending verzenden.",
    "Maak of kies foto's",
    "foto's geselecteerd",
    "Geen foto geselecteerd.",
    "Zichtbare code (optioneel)",
    "Wat ging er mis? (optioneel)",
    "E-mail voor ons antwoord",
    "Alleen gebruikt om te reageren op deze inzending.",
    "Toestemming vereist.",
    "Ik bevestig dat dit mijn foto's zijn en geef Cosmetics Batch toestemming om de foto's en mijn e-mailadres op te slaan, contact met mij op te nemen over deze inzending en geverifieerde fotogedeelten te gebruiken om de openbare gidsen te verbeteren. Persoonlijke gegevens mogen niet zichtbaar zijn.",
    "De foto's konden niet worden verzonden. Probeer kleinere JPEG-, PNG- of WebP-afbeeldingen.",
    "Verzenden…",
    "Verzenden voor beoordeling",
    "Kies maximaal 3 JPEG-, PNG- of WebP-afbeeldingen uit uw camera of galerij. Elke afbeelding wordt vóór het uploaden vergroot of verkleind en opnieuw gecodeerd om de ingesloten locatiemetagegevens te verwijderen. Maximaal: 5 MB per verwerkte afbeelding. Vermijd het opnemen van gezichten of andere persoonlijke details."
  ],
  "pl": [
    "Nie możesz znaleźć lub odczytać kodu BRANDNAME?",
    "Wyślij wyraźne zdjęcia podstawy, etykiety lub pudełka. Przeanalizujemy je i ulepszymy nasze przykłady.",
    "Wyślij zdjęcia kodu",
    "Otrzymano zdjęcie",
    "Sprawdzimy kod i odpowiemy na adres EMAILADDRESS.",
    "Przed wysłaniem wybierz co najmniej jedno zdjęcie w formacie JPEG, PNG lub WebP.",
    "W jednym zgłoszeniu możesz przesłać maksymalnie 3 zdjęcia.",
    "Zrób lub wybierz zdjęcia",
    "wybrane zdjęcia",
    "Nie wybrano zdjęcia.",
    "Widoczny kod (opcjonalnie)",
    "Co poszło nie tak? (opcjonalnie)",
    "Wyślij e-mail z naszą odpowiedzią",
    "Służy wyłącznie do odpowiadania na to zgłoszenie.",
    "Wymagane pozwolenie.",
    "Potwierdzam, że są to moje zdjęcia i zezwalam firmie Cosmetics Batch na przechowywanie zdjęć i mojego adresu e-mail, kontaktowanie się ze mną w sprawie tego zgłoszenia oraz wykorzystywanie zweryfikowanych fragmentów zdjęć do ulepszania swoich publicznych przewodników. Dane osobowe nie powinny być widoczne.",
    "Nie udało się wysłać zdjęć. Spróbuj użyć mniejszych obrazów JPEG, PNG lub WebP.",
    "Wysyłam…",
    "Wyślij do sprawdzenia",
    "Wybierz maksymalnie 3 obrazy JPEG, PNG lub WebP ze swojego aparatu lub galerii. Przed przesłaniem każdy obraz jest zmieniany i ponownie kodowany, aby usunąć osadzone metadane lokalizacji. Maksymalnie: 5 MB na przetworzony obraz. Unikaj podawania twarzy i innych danych osobowych."
  ],
  "sv": [
    "Kan du inte hitta eller läsa BRANDNAME-koden?",
    "Skicka tydliga bilder av basen, etiketten eller kartongen. Vi kommer att granska dem och förbättra våra exempel.",
    "Skicka kodbilder",
    "Foto mottaget",
    "Vi granskar koden och svarar på EMAILADDRESS.",
    "Välj minst ett JPEG-, PNG- eller WebP-foto innan du skickar.",
    "Du kan skicka upp till 3 bilder i en inlämning.",
    "Ta eller välj foton",
    "valda foton",
    "Inget foto valt.",
    "Synlig kod (valfritt)",
    "Vad gick fel? (valfritt)",
    "Maila för vårt svar",
    "Används endast för att svara om detta inlägg.",
    "Tillstånd krävs.",
    "Jag bekräftar att det här är mina bilder och tillåter Cosmetics Batch att lagra bilderna och min e-post, kontakta mig angående denna inlämning och använda verifierade fotodelar för att förbättra sina offentliga guider. Personuppgifter ska inte vara synliga.",
    "Bilderna kunde inte skickas. Försök med mindre JPEG-, PNG- eller WebP-bilder.",
    "Skickar...",
    "Skicka för granskning",
    "Välj upp till 3 JPEG-, PNG- eller WebP-bilder från din kamera eller ditt galleri. Varje bild ändras i storlek och omkodas innan uppladdning för att ta bort inbäddad platsmetadata. Max: 5 MB per bearbetad bild. Undvik att inkludera ansikten eller andra personliga detaljer."
  ],
  "uk": [
    "Не можете знайти або прочитати код BRANDNAME?",
    "Надішліть чіткі фотографії основи, етикетки чи коробки. Ми переглянемо їх і вдосконалимо наші приклади.",
    "Надішліть фотографії коду",
    "Фото отримано",
    "Ми переглянемо код і відповімо на EMAILADDRESS.",
    "Перед надсиланням виберіть принаймні одну фотографію JPEG, PNG або WebP.",
    "Ви можете надіслати до 3 фотографій за один раз.",
    "Зробіть або виберіть фотографії",
    "вибрано фото",
    "Фото не вибрано.",
    "Видимий код (необов'язково)",
    "Що пішло не так? (необов'язково)",
    "Надішліть нам відповідь електронною поштою",
    "Використовується лише для відповіді на це повідомлення.",
    "Потрібен дозвіл.",
    "Я підтверджую, що це мої фотографії, і дозволяю Cosmetics Batch зберігати фотографії та мою електронну пошту, зв’язуватися зі мною щодо цього надсилання та використовувати перевірені частини фотографій для покращення своїх публічних посібників. Особисті дані не повинні бути видні.",
    "Не вдалося надіслати фотографії. Будь ласка, спробуйте менші зображення JPEG, PNG або WebP.",
    "Надсилання…",
    "Надіслати на перевірку",
    "Виберіть до 3 зображень JPEG, PNG або WebP зі своєї камери чи галереї. Розмір кожного зображення змінюється та повторно кодується перед завантаженням, щоб видалити вбудовані метадані про місцезнаходження. Максимум: 5 МБ на оброблене зображення. Уникайте вказувати обличчя чи інші особисті дані."
  ],
  "el": [
    "Δεν μπορείτε να βρείτε ή να διαβάσετε τον κωδικό BRANDNAME;",
    "Στείλτε καθαρές φωτογραφίες της βάσης, της ετικέτας ή του κουτιού. Θα τα εξετάσουμε και θα βελτιώσουμε τα παραδείγματά μας.",
    "Στείλτε φωτογραφίες κωδικού",
    "Η φωτογραφία ελήφθη",
    "Θα ελέγξουμε τον κωδικό και θα απαντήσουμε στο EMAILADDRESS.",
    "Επιλέξτε τουλάχιστον μία φωτογραφία JPEG, PNG ή WebP πριν την αποστολή.",
    "Μπορείτε να στείλετε έως και 3 φωτογραφίες σε μία υποβολή.",
    "Τραβήξτε ή επιλέξτε φωτογραφίες",
    "επιλεγμένες φωτογραφίες",
    "Δεν έχει επιλεγεί φωτογραφία.",
    "Ορατός κωδικός (προαιρετικό)",
    "Τι πήγε στραβά; (προαιρετικό)",
    "Email για την απάντησή μας",
    "Χρησιμοποιείται μόνο για απάντηση σχετικά με αυτήν την υποβολή.",
    "Απαιτείται άδεια.",
    "Επιβεβαιώνω ότι αυτές είναι οι φωτογραφίες μου και επιτρέπω στο Cosmetics Batch να αποθηκεύσει τις φωτογραφίες και το email μου, να επικοινωνήσει μαζί μου σχετικά με αυτήν την υποβολή και να χρησιμοποιήσει επαληθευμένα τμήματα φωτογραφιών για να βελτιώσει τους δημόσιους οδηγούς του. Τα προσωπικά στοιχεία δεν πρέπει να είναι ορατά.",
    "Δεν ήταν δυνατή η αποστολή των φωτογραφιών. Δοκιμάστε μικρότερες εικόνες JPEG, PNG ή WebP.",
    "Αποστολή…",
    "Αποστολή για έλεγχο",
    "Επιλέξτε έως και 3 εικόνες JPEG, PNG ή WebP από την κάμερα ή τη συλλογή σας. Κάθε εικόνα αλλάζει μέγεθος και κωδικοποιείται εκ νέου πριν από τη μεταφόρτωση για να αφαιρεθούν τα ενσωματωμένα μεταδεδομένα τοποθεσίας. Μέγιστο: 5 MB ανά επεξεργασμένη εικόνα. Αποφύγετε να συμπεριλάβετε πρόσωπα ή άλλα προσωπικά στοιχεία."
  ],
  "cs": [
    "Nemůžete najít nebo přečíst kód BRANDNAME?",
    "Pošlete jasné fotografie základny, štítku nebo krabice. Zkontrolujeme je a vylepšíme naše příklady.",
    "Pošlete kódové fotografie",
    "Fotografie přijata",
    "Kód zkontrolujeme a odpovíme na adresu EMAILADDRESS.",
    "Před odesláním vyberte alespoň jednu fotografii JPEG, PNG nebo WebP.",
    "V jednom příspěvku můžete poslat až 3 fotografie.",
    "Pořiďte nebo vyberte fotografie",
    "vybrané fotografie",
    "Nebyla vybrána žádná fotka.",
    "Viditelný kód (volitelné)",
    "Co se pokazilo? (volitelné)",
    "Email pro naši odpověď",
    "Používá se pouze k odpovědi na tento příspěvek.",
    "Vyžaduje se povolení.",
    "Potvrzuji, že se jedná o mé fotografie a povoluji společnosti Cosmetics Batch ukládat fotografie a můj e-mail, kontaktovat mě ohledně tohoto příspěvku a používat ověřené části fotografií k vylepšení svých veřejných průvodců. Osobní údaje by neměly být viditelné.",
    "Fotografie se nepodařilo odeslat. Zkuste prosím menší obrázky JPEG, PNG nebo WebP.",
    "Odesílání…",
    "Odeslat ke kontrole",
    "Vyberte si až 3 obrázky JPEG, PNG nebo WebP z fotoaparátu nebo galerie. Před nahráním se změní velikost každého obrázku a znovu se zakóduje, aby se odstranila vložená metadata o poloze. Maximum: 5 MB na zpracovaný obrázek. Vyhněte se uvádění tváří nebo jiných osobních údajů."
  ],
  "nb": [
    "Kan du ikke finne eller lese BRANDNAME-koden?",
    "Send klare bilder av basen, etiketten eller boksen. Vi vil vurdere dem og forbedre eksemplene våre.",
    "Send kodebilder",
    "Bilde mottatt",
    "Vi går gjennom koden og svarer på EMAILADDRESS.",
    "Velg minst ett JPEG-, PNG- eller WebP-bilde før du sender.",
    "Du kan sende inntil 3 bilder i en innsending.",
    "Ta eller velg bilder",
    "bilder valgt",
    "Ingen bilder er valgt.",
    "Synlig kode (valgfritt)",
    "Hva gikk galt? (valgfritt)",
    "E-post for vårt svar",
    "Brukes kun til å svare på denne innsendingen.",
    "Tillatelse kreves.",
    "Jeg bekrefter at dette er bildene mine og lar Cosmetics Batch lagre bildene og e-posten min, kontakte meg angående denne innsendingen og bruke bekreftede bildedeler for å forbedre sine offentlige veiledninger. Personopplysninger skal ikke være synlige.",
    "Bildene kunne ikke sendes. Prøv mindre JPEG-, PNG- eller WebP-bilder.",
    "Sender …",
    "Send til vurdering",
    "Velg opptil 3 JPEG-, PNG- eller WebP-bilder fra kameraet eller galleriet ditt. Hvert bilde endres størrelse og kodes på nytt før opplasting for å fjerne innebygde stedsmetadata. Maksimalt: 5 MB per behandlet bilde. Unngå å inkludere ansikter eller andre personlige detaljer."
  ],
  "da": [
    "Kan du ikke finde eller læse BRANDNAME-koden?",
    "Send klare billeder af basen, etiketten eller æsken. Vi vil gennemgå dem og forbedre vores eksempler.",
    "Send kodebilleder",
    "Foto modtaget",
    "Vi gennemgår koden og svarer på EMAILADDRESS.",
    "Vælg mindst ét JPEG-, PNG- eller WebP-billede før afsendelse.",
    "Du kan sende op til 3 billeder i én indsendelse.",
    "Tag eller vælg billeder",
    "billeder valgt",
    "Intet billede er valgt.",
    "Synlig kode (valgfrit)",
    "Hvad gik galt? (valgfrit)",
    "E-mail for vores svar",
    "Bruges kun til at svare om dette indlæg.",
    "Tilladelse påkrævet.",
    "Jeg bekræfter, at dette er mine billeder og giver Cosmetics Batch tilladelse til at gemme billederne og min e-mail, kontakte mig om denne indsendelse og bruge verificerede fotodele til at forbedre sine offentlige vejledninger. Personlige oplysninger bør ikke være synlige.",
    "Billederne kunne ikke sendes. Prøv venligst mindre JPEG-, PNG- eller WebP-billeder.",
    "Sender...",
    "Send til gennemgang",
    "Vælg op til 3 JPEG-, PNG- eller WebP-billeder fra dit kamera eller galleri. Hvert billede ændres i størrelse og omkodes før upload for at fjerne integrerede lokationsmetadata. Maksimum: 5 MB pr. behandlet billede. Undgå at inkludere ansigter eller andre personlige detaljer."
  ],
  "fi": [
    "Etkö löydä tai lue BRANDNAME-koodia?",
    "Lähetä selkeitä kuvia alustasta, tarrasta tai laatikosta. Tarkistamme ne ja parannamme esimerkkejämme.",
    "Lähetä koodikuvia",
    "Kuva vastaanotettu",
    "Tarkistamme koodin ja vastaamme osoitteeseen EMAILADDRESS.",
    "Valitse vähintään yksi JPEG-, PNG- tai WebP-kuva ennen lähettämistä.",
    "Voit lähettää enintään 3 kuvaa yhdellä lähetyksellä.",
    "Ota tai valitse valokuvia",
    "valokuvat valittu",
    "Valokuvaa ei ole valittu.",
    "Näkyvä koodi (valinnainen)",
    "Mikä meni pieleen? (valinnainen)",
    "Sähköposti vastausta varten",
    "Käytetään vain vastaamiseen tähän lähetykseen.",
    "Lupa vaaditaan.",
    "Vahvistan, että nämä ovat minun kuviani ja annan Cosmetics Batchin tallentaa valokuvat ja sähköpostini, ottaa minuun yhteyttä tästä lähetyksestä ja käyttää vahvistettuja valokuvaosia julkisten oppaiden parantamiseen. Henkilötiedot eivät saa olla näkyvissä.",
    "Kuvia ei voitu lähettää. Kokeile pienempiä JPEG-, PNG- tai WebP-kuvia.",
    "Lähetetään…",
    "Lähetä tarkistettavaksi",
    "Valitse jopa 3 JPEG-, PNG- tai WebP-kuvaa kamerasta tai galleriasta. Kunkin kuvan kokoa muutetaan ja se koodataan uudelleen ennen latausta upotetun sijainnin metatietojen poistamiseksi. Enintään: 5 Mt per käsitelty kuva. Vältä kasvojen tai muiden henkilökohtaisten tietojen sisällyttämistä."
  ],
  "ro": [
    "Nu puteți găsi sau citi codul BRANDNAME?",
    "Trimiteți fotografii clare ale bazei, etichetei sau cutiei. Le vom revizui și vom îmbunătăți exemplele noastre.",
    "Trimite fotografii cu cod",
    "Fotografie primită",
    "Vom examina codul și vom răspunde la EMAILADDRESS.",
    "Alegeți cel puțin o fotografie JPEG, PNG sau WebP înainte de a trimite.",
    "Puteți trimite până la 3 fotografii într-o singură trimitere.",
    "Faceți sau alegeți fotografii",
    "fotografiile selectate",
    "Nicio fotografie selectată.",
    "Cod vizibil (opțional)",
    "Ce a mers prost? (optional)",
    "E-mail pentru răspunsul nostru",
    "Folosit doar pentru a răspunde despre această trimitere.",
    "Este necesară permisiunea.",
    "Confirm că acestea sunt fotografiile mele și permit Cosmetics Batch să stocheze fotografiile și e-mailul meu, să mă contacteze în legătură cu această trimitere și să folosească porțiuni de fotografii verificate pentru a-și îmbunătăți ghidurile publice. Detaliile personale nu ar trebui să fie vizibile.",
    "Fotografiile nu au putut fi trimise. Încercați imagini JPEG, PNG sau WebP mai mici.",
    "Se trimite…",
    "Trimite pentru revizuire",
    "Alegeți până la 3 imagini JPEG, PNG sau WebP din camera foto sau din galerie. Fiecare imagine este redimensionată și re-codificată înainte de încărcare pentru a elimina metadatele de locație încorporate. Maxim: 5 MB per imagine procesată. Evitați includerea fețelor sau a altor detalii personale."
  ],
  "hu": [
    "Nem találja vagy olvassa el a BRANDNAME kódot?",
    "Küldjön tiszta fényképeket az alapról, címkéről vagy dobozról. Áttekintjük őket, és javítjuk a példáinkat.",
    "Kódfotók küldése",
    "Fénykép érkezett",
    "Ellenőrizzük a kódot, és válaszolunk az EMAILADDRESS címre.",
    "Elküldés előtt válasszon legalább egy JPEG, PNG vagy WebP fotót.",
    "Egy beküldésben legfeljebb 3 fotót küldhetsz.",
    "Készítsen vagy válasszon fényképeket",
    "kiválasztott fényképek",
    "Nincs fotó kiválasztva.",
    "Látható kód (nem kötelező)",
    "Mi történt rosszul? (nem kötelező)",
    "E-mail a válaszunkért",
    "Csak az előterjesztéssel kapcsolatos válaszadásra szolgál.",
    "Engedély szükséges.",
    "Megerősítem, hogy ezek az én képeim, és engedélyezem a Cosmetics Batch számára, hogy tárolja a fotókat és az e-mailjeimet, felvegye velem a kapcsolatot ezzel a beadással kapcsolatban, és felhasználja az ellenőrzött fotórészleteket nyilvános útmutatóinak fejlesztésére. A személyes adatok nem lehetnek láthatóak.",
    "A fényképeket nem sikerült elküldeni. Kérjük, próbálkozzon kisebb JPEG, PNG vagy WebP képekkel.",
    "Küldés…",
    "Küldje el felülvizsgálatra",
    "Válasszon legfeljebb 3 JPEG, PNG vagy WebP képet a kamerájából vagy a galériából. A beágyazott hely metaadatok eltávolítása érdekében minden egyes képet átméreteznek és újrakódolnak a feltöltés előtt. Maximum: 5 MB feldolgozott képenként. Kerülje az arcok vagy egyéb személyes adatok feltüntetését."
  ],
  "ca": [
    "No trobeu ni llegiu el codi BRANDNAME?",
    "Envieu fotos clares de la base, l'etiqueta o la caixa. Els revisarem i millorarem els nostres exemples.",
    "Envia fotos del codi",
    "Foto rebuda",
    "Revisarem el codi i respondrem a EMAILADDRESS.",
    "Trieu almenys una foto JPEG, PNG o WebP abans d'enviar-la.",
    "Podeu enviar fins a 3 fotografies en un sol enviament.",
    "Fes o tria fotos",
    "fotografies seleccionades",
    "No s'ha seleccionat cap foto.",
    "Codi visible (opcional)",
    "Què va fallar? (opcional)",
    "Correu electrònic per a la nostra resposta",
    "S'utilitza només per respondre sobre aquest enviament.",
    "Cal permís.",
    "Confirmo que aquestes són les meves fotos i permeto que Cosmetics Batch emmagatzemi les fotos i el meu correu electrònic, contacti amb mi sobre aquest enviament i utilitzi parts de fotos verificades per millorar les seves guies públiques. Les dades personals no han de ser visibles.",
    "No s'han pogut enviar les fotos. Proveu imatges JPEG, PNG o WebP més petites.",
    "S'està enviant…",
    "Envia a revisió",
    "Trieu fins a 3 imatges JPEG, PNG o WebP de la vostra càmera o galeria. Cada imatge es canvia de mida i es torna a codificar abans de penjar-la per eliminar les metadades d'ubicació incrustades. Màxim: 5 MB per imatge processada. Eviteu incloure cares o altres dades personals."
  ],
  "sr": [
    "Не можете да пронађете или прочитате BRANDNAME код?",
    "Пошаљите јасне фотографије базе, етикете или кутије. Прегледаћемо их и побољшати наше примере.",
    "Пошаљите слике кода",
    "Фотографија примљена",
    "Прегледаћемо код и одговорити на EMAILADDRESS.",
    "Изаберите најмање једну ЈПЕГ, ПНГ или ВебП фотографију пре слања.",
    "Можете послати до 3 фотографије у једној пријави.",
    "Снимите или изаберите фотографије",
    "изабране фотографије",
    "Није изабрана ниједна фотографија.",
    "Видљиви код (опционо)",
    "Шта је пошло по злу? (опционо)",
    "Е-маил за наш одговор",
    "Користи се само за одговор о овом поднеску.",
    "Потребна је дозвола.",
    "Потврђујем да су ово моје фотографије и дозвољавам Цосметицс Батцх-у да чува фотографије и моју е-пошту, контактира ме у вези са овом пријавом и користи проверене делове фотографија да побољша своје јавне водиче. Лични подаци не би требало да буду видљиви.",
    "Фотографије није било могуће послати. Покушајте са мањим ЈПЕГ, ПНГ или ВебП сликама.",
    "Шаље се…",
    "Пошаљите на преглед",
    "Изаберите до 3 ЈПЕГ, ПНГ или ВебП слике са своје камере или галерије. Свака слика се мења величина и поново кодира пре отпремања да би се уклонили уграђени метаподаци о локацији. Максимум: 5 МБ по обрађеној слици. Избегавајте укључивање лица или других личних података."
  ],
  "bg": [
    "Не можете да намерите или прочетете кода на BRANDNAME?",
    "Изпратете ясни снимки на основата, етикета или кутията. Ще ги прегледаме и ще подобрим нашите примери.",
    "Изпратете снимки с код",
    "Снимката е получена",
    "Ще прегледаме кода и ще отговорим на EMAILADDRESS.",
    "Изберете поне една JPEG, PNG или WebP снимка, преди да изпратите.",
    "Можете да изпратите до 3 снимки в едно изпращане.",
    "Направете или изберете снимки",
    "избрани снимки",
    "Няма избрана снимка.",
    "Видим код (по избор)",
    "Какво се обърка? (по избор)",
    "Изпратете имейл за нашия отговор",
    "Използва се само за отговор относно това изпращане.",
    "Изисква се разрешение.",
    "Потвърждавам, че това са мои снимки и позволявам на Cosmetics Batch да съхранява снимките и имейла ми, да се свързва с мен относно това изпращане и да използва проверени части от снимки, за да подобри своите публични ръководства. Личните данни не трябва да се виждат.",
    "Снимките не можаха да бъдат изпратени. Моля, опитайте с по-малки JPEG, PNG или WebP изображения.",
    "Изпращане...",
    "Изпратете за преглед",
    "Изберете до 3 JPEG, PNG или WebP изображения от вашата камера или галерия. Всяко изображение се преоразмерява и прекодира преди качване, за да се премахнат вградените метаданни за местоположение. Максимум: 5 MB на обработено изображение. Избягвайте включването на лица или други лични данни."
  ],
  "sk": [
    "Nemôžete nájsť alebo prečítať kód BRANDNAME?",
    "Pošlite jasné fotografie základne, štítku alebo krabice. Skontrolujeme ich a vylepšíme naše príklady.",
    "Pošlite kódové fotografie",
    "Fotografia prijatá",
    "Kód skontrolujeme a odpovieme na adresu EMAILADDRESS.",
    "Pred odoslaním vyberte aspoň jednu fotografiu vo formáte JPEG, PNG alebo WebP.",
    "V jednom príspevku môžete poslať až 3 fotografie.",
    "Nasnímajte alebo vyberte fotografie",
    "vybraté fotografie",
    "Nie je vybratá žiadna fotografia.",
    "Viditeľný kód (voliteľné)",
    "Čo sa pokazilo? (voliteľné)",
    "E-mail pre našu odpoveď",
    "Používa sa iba na odpoveď na tento príspevok.",
    "Vyžaduje sa povolenie.",
    "Potvrdzujem, že toto sú moje fotografie a povoľujem Cosmetics Batch ukladať fotografie a môj e-mail, kontaktovať ma ohľadom tohto príspevku a používať overené časti fotografií na zlepšenie svojich verejných sprievodcov. Osobné údaje by nemali byť viditeľné.",
    "Fotografie sa nepodarilo odoslať. Skúste menšie obrázky JPEG, PNG alebo WebP.",
    "Odosiela sa…",
    "Odoslať na kontrolu",
    "Vyberte si až 3 obrázky JPEG, PNG alebo WebP z fotoaparátu alebo galérie. Pred odovzdaním sa zmení veľkosť každého obrázka a znova sa zakóduje, aby sa odstránili vložené metadáta polohy. Maximálne: 5 MB na spracovaný obrázok. Vyhnite sa uvádzaniu tvárí alebo iných osobných údajov."
  ],
  "ja": [
    "BRANDNAME コードが見つからない、または読み取れない場合は、",
    "ベース、ラベル、または箱の鮮明な写真を送信してください。それらを確認し、例を改善します。",
    "コード写真を送信する",
    "写真を受け取りました",
    "コードを確認し、EMAILADDRESS に返信します。",
    "送信する前に、JPEG、PNG、または WebP 写真を少なくとも 1 枚選択してください。",
    "1回の投稿で写真は3枚まで送信できます。",
    "写真を撮るか選択する",
    "選択された写真",
    "写真が選択されていません。",
    "可視コード (オプション)",
    "何が間違っていたのでしょうか? (オプション)",
    "返信用メール",
    "この提出物について返信するためにのみ使用されます。",
    "許可が必要です。",
    "私はこれらが私の写真であることを確認し、Cosmetics Batch が写真と私の電子メールを保存し、この投稿について私に連絡し、公開ガイドを改善するために検証済みの写真部分を使用することを許可します。個人情報は表示されるべきではありません。",
    "写真を送信できませんでした。より小さい JPEG、PNG、または WebP 画像を試してください。",
    "送信中…",
    "レビューのために送信する",
    "カメラまたはギャラリーから最大 3 つの JPEG、PNG、または WebP 画像を選択します。各画像はアップロード前にサイズ変更され、再エンコードされて、埋め込まれた位置メタデータが削除されます。最大: 処理された画像ごとに 5 MB。顔やその他の個人情報を含めないでください。"
  ],
  "ko": [
    "BRANDNAME 코드를 찾거나 읽을 수 없습니까?",
    "베이스, 라벨 또는 상자의 선명한 사진을 보내십시오. 우리는 이를 검토하고 예제를 개선할 것입니다.",
    "코드 사진 보내기",
    "사진 수신됨",
    "코드를 검토한 후 EMAILADDRESS에 회신해 드리겠습니다.",
    "보내기 전에 JPEG, PNG 또는 WebP 사진을 하나 이상 선택하세요.",
    "한 번의 제출로 최대 3장의 사진을 보낼 수 있습니다.",
    "사진 촬영 또는 선택",
    "선택한 사진",
    "선택한 사진이 없습니다.",
    "보이는 코드(선택사항)",
    "무엇이 잘못되었나요? (선택사항)",
    "답변을 이메일로 보내주세요",
    "이 제출물에 대해 답변하는 데에만 사용됩니다.",
    "허가가 필요합니다.",
    "나는 이것이 내 사진임을 확인하고 Cosmetics Batch가 사진과 내 이메일을 저장하고, 이 제출물에 대해 나에게 연락하고, 확인된 사진 부분을 사용하여 공개 가이드를 개선하는 것을 허용합니다. 개인정보가 노출되어서는 안 됩니다.",
    "사진을 전송할 수 없습니다. 더 작은 JPEG, PNG 또는 WebP 이미지를 사용해 보세요.",
    "보내는 중…",
    "검토를 위해 보내기",
    "카메라나 갤러리에서 최대 3개의 JPEG, PNG 또는 WebP 이미지를 선택하세요. 삽입된 위치 메타데이터를 제거하기 위해 업로드하기 전에 각 이미지의 크기가 조정되고 다시 인코딩됩니다. 최대: 처리된 이미지당 5MB. 얼굴이나 기타 개인 정보는 포함하지 마세요."
  ],
  "hi": [
    "BRANDNAME का कोड ढूंढ या पढ़ नहीं पा रहे हैं?",
    "आधार, लेबल या बॉक्स की स्पष्ट तस्वीरें भेजें। हम उनकी समीक्षा करेंगे और अपने उदाहरणों में सुधार करेंगे।",
    "कोड फ़ोटो भेजें",
    "फोटो प्राप्त हुआ",
    "हम कोड की समीक्षा करेंगे और EMAILADDRESS का उत्तर देंगे।",
    "भेजने से पहले कम से कम एक JPEG, PNG या WebP फ़ोटो चुनें।",
    "आप एक सबमिशन में अधिकतम 3 फ़ोटो भेज सकते हैं।",
    "फ़ोटो लें या चुनें",
    "फ़ोटो चयनित",
    "कोई फ़ोटो चयनित नहीं.",
    "दृश्यमान कोड (वैकल्पिक)",
    "क्या ग़लत हुआ? (वैकल्पिक)",
    "हमारे उत्तर के लिए ईमेल करें",
    "इसका उपयोग केवल इस सबमिशन के बारे में उत्तर देने के लिए किया जाता है।",
    "अनुमति आवश्यक है.",
    "मैं पुष्टि करता हूं कि ये मेरी तस्वीरें हैं और कॉस्मेटिक्स बैच को तस्वीरें और मेरा ईमेल संग्रहीत करने, इस सबमिशन के बारे में मुझसे संपर्क करने और अपने सार्वजनिक गाइडों को बेहतर बनाने के लिए सत्यापित फोटो भागों का उपयोग करने की अनुमति देता हूं। व्यक्तिगत विवरण दिखाई नहीं देना चाहिए.",
    "तस्वीरें नहीं भेजी जा सकीं. कृपया छोटी JPEG, PNG या WebP छवियाँ आज़माएँ।",
    "भेजा जा रहा है...",
    "समीक्षा हेतु भेजें",
    "अपने कैमरे या गैलरी से अधिकतम 3 JPEG, PNG या WebP छवियाँ चुनें। एम्बेडेड स्थान मेटाडेटा को हटाने के लिए अपलोड करने से पहले प्रत्येक छवि का आकार बदला और पुनः एन्कोड किया गया है। अधिकतम: 5 एमबी प्रति संसाधित छवि। चेहरे या अन्य व्यक्तिगत विवरण शामिल करने से बचें।"
  ],
  "id": [
    "Tidak dapat menemukan atau membaca kode BRANDNAME?",
    "Kirimkan foto dasar, label, atau kotak yang jelas. Kami akan meninjaunya dan menyempurnakan contoh kami.",
    "Kirim foto kode",
    "Foto diterima",
    "Kami akan meninjau kode dan membalas EMAILADDRESS.",
    "Pilih setidaknya satu foto JPEG, PNG, atau WebP sebelum dikirim.",
    "Anda dapat mengirim maksimal 3 foto dalam satu pengiriman.",
    "Ambil atau pilih foto",
    "foto dipilih",
    "Tidak ada foto yang dipilih.",
    "Kode yang terlihat (opsional)",
    "Apa yang salah? (opsional)",
    "Email untuk balasan kami",
    "Digunakan hanya untuk membalas kiriman ini.",
    "Izin diperlukan.",
    "Saya mengonfirmasi bahwa ini adalah foto saya dan mengizinkan Batch Kosmetik untuk menyimpan foto dan email saya, menghubungi saya tentang pengiriman ini, dan menggunakan bagian foto yang terverifikasi untuk menyempurnakan panduan publiknya. Detail pribadi tidak boleh terlihat.",
    "Foto tidak dapat dikirim. Silakan coba gambar JPEG, PNG, atau WebP yang lebih kecil.",
    "Mengirim…",
    "Kirim untuk ditinjau",
    "Pilih hingga 3 gambar JPEG, PNG, atau WebP dari kamera atau galeri Anda. Setiap gambar diubah ukurannya dan dikodekan ulang sebelum diunggah untuk menghapus metadata lokasi yang disematkan. Maksimum: 5 MB per gambar yang diproses. Hindari menyertakan wajah atau detail pribadi lainnya."
  ],
  "vi": [
    "Không thể tìm thấy hoặc đọc mã BRANDNAME?",
    "Gửi hình ảnh rõ ràng về đế, nhãn hoặc hộp. Chúng tôi sẽ xem xét chúng và cải thiện các ví dụ của chúng tôi.",
    "Gửi ảnh mã",
    "Đã nhận được ảnh",
    "Chúng tôi sẽ xem xét mã và trả lời EMAILADDRESS.",
    "Chọn ít nhất một ảnh JPEG, PNG hoặc WebP trước khi gửi.",
    "Bạn có thể gửi tối đa 3 ảnh trong một lần gửi.",
    "Chụp hoặc chọn ảnh",
    "ảnh đã chọn",
    "Không có ảnh nào được chọn.",
    "Mã hiển thị (tùy chọn)",
    "Điều gì đã xảy ra? (tùy chọn)",
    "Email để trả lời của chúng tôi",
    "Chỉ được sử dụng để trả lời về bài nộp này.",
    "Cần có sự cho phép.",
    "Tôi xác nhận đây là ảnh của tôi và cho phép Cosmetics Batch lưu trữ ảnh và email của tôi, liên hệ với tôi về việc gửi này và sử dụng các phần ảnh đã được xác minh để cải thiện hướng dẫn công khai của mình. Thông tin cá nhân không nên được nhìn thấy.",
    "Không thể gửi ảnh. Vui lòng thử hình ảnh JPEG, PNG hoặc WebP nhỏ hơn.",
    "Đang gửi…",
    "Gửi để xem xét",
    "Chọn tối đa 3 hình ảnh JPEG, PNG hoặc WebP từ máy ảnh hoặc thư viện của bạn. Mỗi hình ảnh được thay đổi kích thước và mã hóa lại trước khi tải lên để xóa siêu dữ liệu vị trí được nhúng. Tối đa: 5 MB cho mỗi hình ảnh được xử lý. Tránh bao gồm khuôn mặt hoặc các chi tiết cá nhân khác."
  ],
  "th": [
    "ไม่พบหรืออ่านรหัส BRANDNAME ใช่ไหม",
    "ส่งรูปฐาน ป้าย หรือกล่องที่ชัดเจน เราจะตรวจสอบและปรับปรุงตัวอย่างของเรา",
    "ส่งภาพรหัส",
    "ได้รับรูปถ่ายแล้ว",
    "เราจะตรวจสอบโค้ดและตอบกลับ EMAILADDRESS",
    "เลือกรูปภาพ JPEG, PNG หรือ WebP อย่างน้อยหนึ่งภาพก่อนส่ง",
    "คุณสามารถส่งภาพถ่ายได้สูงสุด 3 ภาพในการส่งครั้งเดียว",
    "ถ่ายหรือเลือกรูปถ่าย",
    "เลือกรูปภาพแล้ว",
    "ไม่ได้เลือกรูปภาพ",
    "รหัสที่มองเห็นได้ (ไม่บังคับ)",
    "เกิดอะไรขึ้น? (ไม่จำเป็น)",
    "อีเมลสำหรับการตอบกลับของเรา",
    "ใช้เพื่อตอบกลับเกี่ยวกับการส่งนี้เท่านั้น",
    "ต้องได้รับอนุญาต",
    "ฉันยืนยันว่านี่คือรูปถ่ายของฉัน และอนุญาตให้ Cosmetics Batch เก็บรูปภาพและอีเมลของฉัน ติดต่อฉันเกี่ยวกับการส่งนี้ และใช้ส่วนของรูปภาพที่ได้รับการตรวจสอบแล้วเพื่อปรับปรุงคู่มือสาธารณะ ไม่ควรมองเห็นรายละเอียดส่วนบุคคล",
    "ไม่สามารถส่งรูปถ่ายได้ โปรดลองใช้รูปภาพ JPEG, PNG หรือ WebP ที่เล็กลง",
    "กำลังส่ง...",
    "ส่งเพื่อตรวจสอบ",
    "เลือกรูปภาพ JPEG, PNG หรือ WebP ได้สูงสุด 3 รูปจากกล้องหรือแกลเลอรีของคุณ รูปภาพแต่ละรูปจะถูกปรับขนาดและเข้ารหัสใหม่ก่อนอัปโหลดเพื่อลบข้อมูลเมตาของตำแหน่งที่ฝังไว้ สูงสุด: 5 MB ต่อภาพที่ประมวลผล หลีกเลี่ยงการใส่ใบหน้าหรือรายละเอียดส่วนบุคคลอื่นๆ"
  ],
  "ms": [
    "Tidak dapat mencari atau membaca kod BRANDNAME?",
    "Hantar gambar asas, label atau kotak yang jelas. Kami akan menyemaknya dan menambah baik contoh kami.",
    "Hantar foto kod",
    "Foto diterima",
    "Kami akan menyemak kod dan membalas EMAILADDRESS.",
    "Pilih sekurang-kurangnya satu foto JPEG, PNG atau WebP sebelum menghantar.",
    "Anda boleh menghantar sehingga 3 gambar dalam satu penyerahan.",
    "Ambil atau pilih foto",
    "foto dipilih",
    "Tiada foto dipilih.",
    "Kod yang boleh dilihat (pilihan)",
    "Apa yang silap? (pilihan)",
    "E-mel untuk jawapan kami",
    "Digunakan hanya untuk membalas tentang penyerahan ini.",
    "Kebenaran diperlukan.",
    "Saya mengesahkan ini adalah foto saya dan membenarkan Cosmetics Batch menyimpan foto dan e-mel saya, menghubungi saya tentang penyerahan ini dan menggunakan bahagian foto yang disahkan untuk menambah baik panduan awamnya. Butiran peribadi tidak sepatutnya kelihatan.",
    "Foto tidak dapat dihantar. Sila cuba imej JPEG, PNG atau WebP yang lebih kecil.",
    "Menghantar…",
    "Hantar untuk semakan",
    "Pilih sehingga 3 imej JPEG, PNG atau WebP daripada kamera atau galeri anda. Setiap imej diubah saiz dan dikod semula sebelum dimuat naik untuk mengalih keluar metadata lokasi terbenam. Maksimum: 5 MB setiap imej yang diproses. Elakkan memasukkan muka atau butiran peribadi lain."
  ],
  "tl": [
    "Hindi mahanap o mabasa ang BRANDNAME code?",
    "Magpadala ng malilinaw na larawan ng base, label o kahon. Susuriin namin ang mga ito at pagbutihin ang aming mga halimbawa.",
    "Magpadala ng mga larawan ng code",
    "Natanggap ang larawan",
    "Susuriin namin ang code at tutugon sa EMAILADDRESS.",
    "Pumili ng kahit isang JPEG, PNG o WebP na larawan bago ipadala.",
    "Maaari kang magpadala ng hanggang 3 larawan sa isang pagsusumite.",
    "Kumuha o pumili ng mga larawan",
    "mga larawang napili",
    "Walang napiling larawan.",
    "Nakikitang code (opsyonal)",
    "Ano ang nangyaring mali? (opsyonal)",
    "Email para sa aming tugon",
    "Ginagamit lang para tumugon tungkol sa pagsusumiteng ito.",
    "Kinakailangan ang pahintulot.",
    "Kinukumpirma kong ito ang aking mga larawan at pinapayagan ang Cosmetics Batch na iimbak ang mga larawan at ang aking email, makipag-ugnayan sa akin tungkol sa pagsusumiteng ito, at gumamit ng mga na-verify na bahagi ng larawan upang mapabuti ang mga pampublikong gabay nito. Hindi dapat makita ang mga personal na detalye.",
    "Hindi maipadala ang mga larawan. Pakisubukan ang mas maliliit na larawang JPEG, PNG o WebP.",
    "Ipinapadala…",
    "Ipadala para sa pagsusuri",
    "Pumili ng hanggang 3 JPEG, PNG o WebP na mga larawan mula sa iyong camera o gallery. Ang bawat larawan ay binago at muling na-encode bago i-upload upang alisin ang naka-embed na metadata ng lokasyon. Maximum: 5 MB bawat naprosesong larawan. Iwasang magsama ng mga mukha o iba pang personal na detalye."
  ],
  "bn": [
    "BRANDNAME কোডটি খুঁজে পাচ্ছেন বা পড়তে পারছেন না?",
    "বেস, লেবেল বা বাক্সের পরিষ্কার ছবি পাঠান। আমরা সেগুলি পর্যালোচনা করব এবং আমাদের উদাহরণগুলি উন্নত করব।",
    "কোড ছবি পাঠান",
    "ছবি গৃহীত হয়েছে",
    "আমরা কোডটি পর্যালোচনা করব এবং EMAILADDRESS-এ উত্তর দেব।",
    "পাঠানোর আগে অন্তত একটি JPEG, PNG বা WebP ফটো বেছে নিন।",
    "আপনি একটি জমাতে 3টি ফটো পর্যন্ত পাঠাতে পারেন৷",
    "ছবি তুলুন বা বেছে নিন",
    "ছবি নির্বাচিত",
    "কোনো ছবি নির্বাচন করা হয়নি।",
    "দৃশ্যমান কোড (ঐচ্ছিক)",
    "কি ভুল হয়েছে? (ঐচ্ছিক)",
    "আমাদের উত্তর জন্য ইমেল",
    "শুধুমাত্র এই জমা দেওয়ার বিষয়ে উত্তর দিতে ব্যবহৃত হয়।",
    "অনুমতি প্রয়োজন.",
    "আমি নিশ্চিত করি যে এগুলি আমার ফটো এবং কসমেটিক্স ব্যাচকে ফটো এবং আমার ইমেল সংরক্ষণ করার অনুমতি দিই, এই জমা দেওয়ার বিষয়ে আমার সাথে যোগাযোগ করুন এবং এর পাবলিক গাইড উন্নত করতে যাচাইকৃত ফটো অংশগুলি ব্যবহার করুন৷ ব্যক্তিগত বিবরণ দৃশ্যমান করা উচিত নয়.",
    "ছবি পাঠানো যায়নি. ছোট JPEG, PNG বা WebP ছবি চেষ্টা করুন.",
    "পাঠানো হচ্ছে...",
    "পর্যালোচনার জন্য পাঠান",
    "আপনার ক্যামেরা বা গ্যালারি থেকে 3টি পর্যন্ত JPEG, PNG বা WebP ছবি বেছে নিন। এম্বেড করা অবস্থানের মেটাডেটা অপসারণের জন্য আপলোড করার আগে প্রতিটি চিত্রের আকার পরিবর্তন করা হয় এবং পুনরায় এনকোড করা হয়। সর্বাধিক: 5 MB প্রতি প্রক্রিয়াকৃত চিত্র। মুখ বা অন্যান্য ব্যক্তিগত বিবরণ অন্তর্ভুক্ত এড়িয়ে চলুন."
  ],
  "ur": [
    "BRANDNAME کوڈ تلاش یا پڑھ نہیں سکتے؟",
    "بیس، لیبل یا باکس کی واضح تصاویر بھیجیں۔ ہم ان کا جائزہ لیں گے اور اپنی مثالوں کو بہتر بنائیں گے۔",
    "کوڈ کی تصاویر بھیجیں۔",
    "تصویر موصول ہوئی۔",
    "ہم کوڈ کا جائزہ لیں گے اور EMAILADDRESS کو جواب دیں گے۔",
    "بھیجنے سے پہلے کم از کم ایک JPEG، PNG یا WebP تصویر منتخب کریں۔",
    "آپ ایک جمع کرانے میں 3 تصاویر تک بھیج سکتے ہیں۔",
    "تصاویر لیں یا منتخب کریں۔",
    "تصاویر منتخب کی گئیں۔",
    "کوئی تصویر منتخب نہیں کی گئی۔",
    "مرئی کوڈ (اختیاری)",
    "کیا غلط ہوا؟ (اختیاری)",
    "ہمارے جواب کے لیے ای میل کریں۔",
    "صرف اس جمع کرانے کے بارے میں جواب دینے کے لیے استعمال کیا جاتا ہے۔",
    "اجازت درکار ہے۔",
    "میں تصدیق کرتا ہوں کہ یہ میری تصاویر ہیں اور کاسمیٹکس بیچ کو اجازت دیتا ہوں کہ وہ تصاویر اور میرا ای میل ذخیرہ کرے، اس جمع کرانے کے بارے میں مجھ سے رابطہ کریں، اور اس کے عوامی گائیڈز کو بہتر بنانے کے لیے تصویر کے تصدیق شدہ حصے استعمال کریں۔ ذاتی تفصیلات ظاہر نہیں ہونی چاہئیں۔",
    "تصاویر بھیجی نہیں جا سکیں۔ براہ کرم چھوٹی JPEG، PNG یا WebP تصاویر آزمائیں۔",
    "بھیج رہا ہے…",
    "جائزہ کے لیے بھیجیں۔",
    "اپنے کیمرے یا گیلری سے 3 تک JPEG، PNG یا WebP تصاویر منتخب کریں۔ ایمبیڈڈ لوکیشن میٹا ڈیٹا کو ہٹانے کے لیے اپ لوڈ کرنے سے پہلے ہر تصویر کا سائز تبدیل کیا جاتا ہے اور اسے دوبارہ انکوڈ کیا جاتا ہے۔ زیادہ سے زیادہ: 5 MB فی پروسیس شدہ تصویر۔ چہرے یا دیگر ذاتی تفصیلات شامل کرنے سے گریز کریں۔"
  ],
  "ta": [
    "BRANDNAME குறியீட்டைக் கண்டுபிடிக்கவோ படிக்கவோ முடியவில்லையா?",
    "அடிப்படை, லேபிள் அல்லது பெட்டியின் தெளிவான புகைப்படங்களை அனுப்பவும். அவற்றை மதிப்பாய்வு செய்து எங்களின் உதாரணங்களை மேம்படுத்துவோம்.",
    "குறியீட்டு புகைப்படங்களை அனுப்பவும்",
    "புகைப்படம் பெறப்பட்டது",
    "குறியீட்டை மதிப்பாய்வு செய்து EMAILADDRESS க்கு பதிலளிப்போம்.",
    "அனுப்பும் முன் குறைந்தது ஒரு JPEG, PNG அல்லது WebP புகைப்படத்தைத் தேர்வு செய்யவும்.",
    "ஒரு சமர்ப்பிப்பில் 3 படங்கள் வரை அனுப்பலாம்.",
    "புகைப்படங்களை எடுக்கவும் அல்லது தேர்வு செய்யவும்",
    "புகைப்படங்கள் தேர்ந்தெடுக்கப்பட்டன",
    "புகைப்படம் எதுவும் தேர்ந்தெடுக்கப்படவில்லை.",
    "காணக்கூடிய குறியீடு (விரும்பினால்)",
    "என்ன தவறு நடந்தது? (விரும்பினால்)",
    "எங்கள் பதிலுக்கான மின்னஞ்சல்",
    "இந்த சமர்ப்பிப்பைப் பற்றி பதிலளிக்க மட்டுமே பயன்படுத்தப்பட்டது.",
    "அனுமதி தேவை.",
    "இவை எனது புகைப்படங்கள் என்பதை உறுதிசெய்து, அழகுசாதனப் பொருட்களைப் படங்களையும் எனது மின்னஞ்சலையும் சேமிக்கவும், இந்தச் சமர்ப்பிப்பு குறித்து என்னைத் தொடர்பு கொள்ளவும், அதன் பொது வழிகாட்டிகளை மேம்படுத்த சரிபார்க்கப்பட்ட புகைப்படப் பகுதிகளைப் பயன்படுத்தவும் அனுமதிக்கிறேன். தனிப்பட்ட விவரங்கள் தெரியக்கூடாது.",
    "புகைப்படங்களை அனுப்ப முடியவில்லை. சிறிய JPEG, PNG அல்லது WebP படங்களை முயற்சிக்கவும்.",
    "அனுப்புகிறது…",
    "மதிப்பாய்வுக்கு அனுப்பவும்",
    "உங்கள் கேமரா அல்லது கேலரியில் இருந்து 3 JPEG, PNG அல்லது WebP படங்கள் வரை தேர்வு செய்யவும். உட்பொதிக்கப்பட்ட இருப்பிட மெட்டாடேட்டாவை அகற்ற, பதிவேற்றுவதற்கு முன் ஒவ்வொரு படமும் அளவு மாற்றப்பட்டு மீண்டும் குறியாக்கம் செய்யப்படுகிறது. அதிகபட்சம்: செயலாக்கப்பட்ட படத்திற்கு 5 MB. முகங்கள் அல்லது பிற தனிப்பட்ட விவரங்களைச் சேர்ப்பதைத் தவிர்க்கவும்."
  ],
  "te": [
    "BRANDNAME కోడ్‌ని కనుగొనలేదా లేదా చదవలేకపోయారా?",
    "బేస్, లేబుల్ లేదా బాక్స్ యొక్క స్పష్టమైన ఫోటోలను పంపండి. మేము వాటిని సమీక్షించి, మా ఉదాహరణలను మెరుగుపరుస్తాము.",
    "కోడ్ ఫోటోలను పంపండి",
    "ఫోటో అందుకుంది",
    "మేము కోడ్‌ని సమీక్షించి, EMAILADDRESSకి ప్రత్యుత్తరం అందిస్తాము.",
    "పంపే ముందు కనీసం ఒక JPEG, PNG లేదా WebP ఫోటోను ఎంచుకోండి.",
    "మీరు ఒక సమర్పణలో గరిష్టంగా 3 ఫోటోలను పంపవచ్చు.",
    "ఫోటోలను తీయండి లేదా ఎంచుకోండి",
    "ఫోటోలు ఎంపిక చేయబడ్డాయి",
    "ఫోటో ఏదీ ఎంచుకోబడలేదు.",
    "కనిపించే కోడ్ (ఐచ్ఛికం)",
    "ఏం తప్పు జరిగింది? (ఐచ్ఛికం)",
    "మా ప్రత్యుత్తరానికి ఇమెయిల్ చేయండి",
    "ఈ సమర్పణ గురించి ప్రత్యుత్తరం ఇవ్వడానికి మాత్రమే ఉపయోగించబడుతుంది.",
    "అనుమతి అవసరం.",
    "ఇవి నా ఫోటోలు అని నేను ధృవీకరిస్తున్నాను మరియు ఫోటోలు మరియు నా ఇమెయిల్‌లను నిల్వ చేయడానికి సౌందర్య సాధనాల బ్యాచ్‌ని అనుమతిస్తున్నాను, ఈ సమర్పణ గురించి నన్ను సంప్రదించండి మరియు దాని పబ్లిక్ గైడ్‌లను మెరుగుపరచడానికి ధృవీకరించబడిన ఫోటో భాగాలను ఉపయోగిస్తాను. వ్యక్తిగత వివరాలు కనిపించకూడదు.",
    "ఫోటోలు పంపడం సాధ్యం కాలేదు. దయచేసి చిన్న JPEG, PNG లేదా WebP చిత్రాలను ప్రయత్నించండి.",
    "పంపుతోంది...",
    "సమీక్ష కోసం పంపండి",
    "మీ కెమెరా లేదా గ్యాలరీ నుండి గరిష్టంగా 3 JPEG, PNG లేదా WebP చిత్రాలను ఎంచుకోండి. పొందుపరిచిన లొకేషన్ మెటాడేటాను తీసివేయడానికి అప్‌లోడ్ చేయడానికి ముందు ప్రతి చిత్రం పరిమాణం మార్చబడుతుంది మరియు మళ్లీ ఎన్‌కోడ్ చేయబడుతుంది. గరిష్టంగా: ప్రాసెస్ చేయబడిన ప్రతి చిత్రానికి 5 MB. ముఖాలు లేదా ఇతర వ్యక్తిగత వివరాలను చేర్చడం మానుకోండి."
  ],
  "mr": [
    "BRANDNAME कोड शोधू किंवा वाचू शकत नाही?",
    "बेस, लेबल किंवा बॉक्सचे स्पष्ट फोटो पाठवा. आम्ही त्यांचे पुनरावलोकन करू आणि आमची उदाहरणे सुधारू.",
    "कोड फोटो पाठवा",
    "फोटो मिळाला",
    "आम्ही कोडचे पुनरावलोकन करू आणि EMAILADDRESS ला उत्तर देऊ.",
    "पाठवण्यापूर्वी किमान एक JPEG, PNG किंवा WebP फोटो निवडा.",
    "तुम्ही एका सबमिशनमध्ये कमाल 3 फोटो पाठवू शकता.",
    "फोटो घ्या किंवा निवडा",
    "फोटो निवडले",
    "कोणताही फोटो निवडलेला नाही.",
    "दृश्यमान कोड (पर्यायी)",
    "काय चूक झाली? (पर्यायी)",
    "आमच्या उत्तरासाठी ईमेल",
    "फक्त या सबमिशनबद्दल उत्तर देण्यासाठी वापरले.",
    "परवानगी आवश्यक.",
    "मी पुष्टी करतो की हे माझे फोटो आहेत आणि कॉस्मेटिक्स बॅचला फोटो आणि माझा ईमेल संग्रहित करण्याची परवानगी देतो, या सबमिशनबद्दल माझ्याशी संपर्क साधा आणि त्याचे सार्वजनिक मार्गदर्शक सुधारण्यासाठी सत्यापित फोटो भाग वापरा. वैयक्तिक तपशील दृश्यमान नसावेत.",
    "फोटो पाठवता आले नाहीत. कृपया लहान JPEG, PNG किंवा WebP प्रतिमा वापरून पहा.",
    "पाठवत आहे...",
    "पुनरावलोकनासाठी पाठवा",
    "तुमच्या कॅमेरा किंवा गॅलरीमधून 3 JPEG, PNG किंवा WebP प्रतिमा निवडा. एम्बेड केलेला स्थान मेटाडेटा काढण्यासाठी अपलोड करण्यापूर्वी प्रत्येक प्रतिमेचा आकार बदलला जातो आणि पुन्हा एन्कोड केला जातो. कमाल: 5 MB प्रति प्रक्रिया केलेल्या प्रतिमेसाठी. चेहरे किंवा इतर वैयक्तिक तपशील समाविष्ट करणे टाळा."
  ],
  "pa": [
    "BRANDNAME ਕੋਡ ਨੂੰ ਲੱਭ ਜਾਂ ਪੜ੍ਹ ਨਹੀਂ ਸਕਦੇ?",
    "ਬੇਸ, ਲੇਬਲ ਜਾਂ ਡੱਬੇ ਦੀਆਂ ਸਾਫ਼ ਫੋਟੋਆਂ ਭੇਜੋ। ਅਸੀਂ ਉਹਨਾਂ ਦੀ ਸਮੀਖਿਆ ਕਰਕੇ ਆਪਣੀਆਂ ਉਦਾਹਰਣਾਂ ਨੂੰ ਬਿਹਤਰ ਬਣਾਵਾਂਗੇ।",
    "ਕੋਡ ਦੀਆਂ ਫੋਟੋਆਂ ਭੇਜੋ",
    "ਫੋਟੋ ਮਿਲ ਗਈ",
    "ਅਸੀਂ ਕੋਡ ਦੀ ਸਮੀਖਿਆ ਕਰਾਂਗੇ ਅਤੇ EMAILADDRESS 'ਤੇ ਜਵਾਬ ਭੇਜਾਂਗੇ।",
    "ਭੇਜਣ ਤੋਂ ਪਹਿਲਾਂ ਘੱਟੋ-ਘੱਟ ਇੱਕ JPEG, PNG ਜਾਂ WebP ਫੋਟੋ ਚੁਣੋ।",
    "ਤੁਸੀਂ ਇੱਕ ਵਾਰ ਵਿੱਚ ਵੱਧ ਤੋਂ ਵੱਧ 3 ਫੋਟੋਆਂ ਭੇਜ ਸਕਦੇ ਹੋ।",
    "ਫੋਟੋ ਖਿੱਚੋ ਜਾਂ ਚੁਣੋ",
    "ਚੁਣੀਆਂ ਗਈਆਂ ਫੋਟੋਆਂ",
    "ਕੋਈ ਫੋਟੋ ਨਹੀਂ ਚੁਣੀ ਗਈ।",
    "ਦਿਖਾਈ ਦੇ ਰਿਹਾ ਕੋਡ (ਵਿਕਲਪਿਕ)",
    "ਕੀ ਸਮੱਸਿਆ ਆਈ? (ਵਿਕਲਪਿਕ)",
    "ਸਾਡੇ ਜਵਾਬ ਲਈ ਈਮੇਲ",
    "ਇਹ ਸਿਰਫ਼ ਇਸ ਸਬਮਿਸ਼ਨ ਬਾਰੇ ਜਵਾਬ ਦੇਣ ਲਈ ਵਰਤੀ ਜਾਵੇਗੀ।",
    "ਇਜਾਜ਼ਤ ਲੋੜੀਂਦੀ ਹੈ।",
    "ਮੈਂ ਪੁਸ਼ਟੀ ਕਰਦਾ/ਕਰਦੀ ਹਾਂ ਕਿ ਇਹ ਫੋਟੋਆਂ ਮੇਰੀਆਂ ਹਨ। ਮੈਂ Cosmetics Batch ਨੂੰ ਇਹ ਫੋਟੋਆਂ ਅਤੇ ਆਪਣੀ ਈਮੇਲ ਸੰਭਾਲਣ, ਇਸ ਸਬਮਿਸ਼ਨ ਬਾਰੇ ਮੇਰੇ ਨਾਲ ਸੰਪਰਕ ਕਰਨ ਅਤੇ ਜਾਂਚੇ ਹੋਏ ਫੋਟੋ ਹਿੱਸਿਆਂ ਨੂੰ ਜਨਤਕ ਗਾਈਡਾਂ ਸੁਧਾਰਨ ਲਈ ਵਰਤਣ ਦੀ ਇਜਾਜ਼ਤ ਦਿੰਦਾ/ਦਿੰਦੀ ਹਾਂ। ਫੋਟੋਆਂ ਵਿੱਚ ਨਿੱਜੀ ਜਾਣਕਾਰੀ ਨਹੀਂ ਹੋਣੀ ਚਾਹੀਦੀ।",
    "ਫੋਟੋਆਂ ਭੇਜੀਆਂ ਨਹੀਂ ਜਾ ਸਕੀਆਂ। ਕਿਰਪਾ ਕਰਕੇ ਛੋਟੀਆਂ JPEG, PNG ਜਾਂ WebP ਤਸਵੀਰਾਂ ਨਾਲ ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ।",
    "ਭੇਜਿਆ ਜਾ ਰਿਹਾ ਹੈ...",
    "ਸਮੀਖਿਆ ਲਈ ਭੇਜੋ",
    "ਆਪਣੇ ਕੈਮਰੇ ਜਾਂ ਗੈਲਰੀ ਤੋਂ ਵੱਧ ਤੋਂ ਵੱਧ 3 JPEG, PNG ਜਾਂ WebP ਤਸਵੀਰਾਂ ਚੁਣੋ। ਟਿਕਾਣੇ ਨਾਲ ਜੁੜਿਆ ਮੈਟਾਡੇਟਾ ਹਟਾਉਣ ਲਈ ਹਰ ਤਸਵੀਰ ਨੂੰ ਅੱਪਲੋਡ ਤੋਂ ਪਹਿਲਾਂ ਮੁੜ ਆਕਾਰ ਦਿੱਤਾ ਅਤੇ ਇਨਕੋਡ ਕੀਤਾ ਜਾਂਦਾ ਹੈ। ਹਰ ਪ੍ਰੋਸੈਸ ਕੀਤੀ ਤਸਵੀਰ ਦੀ ਵੱਧ ਤੋਂ ਵੱਧ ਹੱਦ 5 MB ਹੈ। ਚਿਹਰੇ ਜਾਂ ਹੋਰ ਨਿੱਜੀ ਜਾਣਕਾਰੀ ਸ਼ਾਮਲ ਨਾ ਕਰੋ।"
  ],
  "gu": [
    "BRANDNAME કોડ શોધી કે વાંચી શકતા નથી?",
    "આધાર, લેબલ અથવા બોક્સના સ્પષ્ટ ફોટા મોકલો. અમે તેમની સમીક્ષા કરીશું અને અમારા ઉદાહરણોને સુધારીશું.",
    "કોડ ફોટા મોકલો",
    "ફોટો મળ્યો",
    "અમે કોડની સમીક્ષા કરીશું અને EMAILADDRESS ને જવાબ આપીશું.",
    "મોકલતા પહેલા ઓછામાં ઓછો એક JPEG, PNG અથવા WebP ફોટો પસંદ કરો.",
    "તમે એક સબમિશનમાં 3 જેટલા ફોટા મોકલી શકો છો.",
    "ફોટા લો અથવા પસંદ કરો",
    "ફોટા પસંદ કર્યા",
    "કોઈ ફોટો પસંદ કર્યો નથી.",
    "દૃશ્યમાન કોડ (વૈકલ્પિક)",
    "શું ખોટું થયું? (વૈકલ્પિક)",
    "અમારા જવાબ માટે ઇમેઇલ",
    "માત્ર આ સબમિશન વિશે જવાબ આપવા માટે વપરાય છે.",
    "પરવાનગી જરૂરી છે.",
    "હું પુષ્ટિ કરું છું કે આ મારા ફોટા છે અને કોસ્મેટિક્સ બેચને ફોટા અને મારા ઇમેઇલને સંગ્રહિત કરવાની મંજૂરી આપું છું, આ સબમિશન વિશે મારો સંપર્ક કરો અને તેના સાર્વજનિક માર્ગદર્શિકાઓને સુધારવા માટે ચકાસાયેલ ફોટો ભાગોનો ઉપયોગ કરો. વ્યક્તિગત વિગતો દૃશ્યમાન હોવી જોઈએ નહીં.",
    "ફોટા મોકલી શકાયા નથી. કૃપા કરીને નાની JPEG, PNG અથવા WebP છબીઓનો પ્રયાસ કરો.",
    "મોકલી રહ્યું છે...",
    "સમીક્ષા માટે મોકલો",
    "તમારા કેમેરા અથવા ગેલેરીમાંથી 3 જેટલી JPEG, PNG અથવા WebP છબીઓ પસંદ કરો. એમ્બેડ કરેલા સ્થાન મેટાડેટાને દૂર કરવા માટે અપલોડ કરતા પહેલા દરેક છબીનું કદ બદલાય છે અને ફરીથી એન્કોડ કરવામાં આવે છે. મહત્તમ: પ્રક્રિયા કરેલ છબી દીઠ 5 MB. ચહેરા અથવા અન્ય વ્યક્તિગત વિગતો શામેલ કરવાનું ટાળો."
  ],
  "yue": [
    "搵唔到或者讀唔到 BRANDNAME 代碼？",
    "傳送底座、標籤或者盒嘅清晰相片。我哋會睇返佢哋同埋改善我哋嘅例子。",
    "傳送代碼相片",
    "收到相片",
    "我哋會檢查代碼，並回覆到 EMAILADDRESS。",
    "喺傳送之前，揀至少一張 JPEG 、 PNG 或者 WebP 相片。",
    "你可以喺一次提交入面發送最多3張相。",
    "影或者揀相",
    "揀咗啲相",
    "冇揀過相片。",
    "可見代碼（可選）",
    "發生咩事？ （可選）",
    "電郵我哋嘅回覆",
    "只係用嚟回覆呢個提交嘅內容。",
    "需要許可。",
    "我確認呢啲係我嘅相片，並且允許 Cosmetics Batch 儲存相片同我嘅電郵，就呢個提交嘅事同我聯絡，同埋用經過驗證嘅相片部分嚟改善佢嘅公開指南。個人資料唔應該睇到。",
    "啲相傳送唔到。請試下細啲嘅 JPEG 、 PNG 或者 WebP 圖片。",
    "發送緊 …",
    "送去審查",
    "喺你部相機或者圖庫入面揀最多3張 JPEG 、 PNG 或者 WebP 圖片。每張圖片都會喺上載之前調整大細同重新編碼，嚟移除嵌入嘅位置元數據。最大：每張處理過嘅圖片5 MB 。避免包括面孔或者其他個人資料。"
  ],
  "uz": [
    "BRANDNAME kodini topa olmayapsizmi yoki o‘qiy olmayapsizmi?",
    "Baza, yorliq yoki qutining aniq fotosuratlarini yuboring. Biz ularni ko'rib chiqamiz va misollarimizni yaxshilaymiz.",
    "Kodli fotosuratlarni yuboring",
    "Surat qabul qilindi",
    "Kodni ko‘rib chiqamiz va EMAILADDRESS manziliga javob beramiz.",
    "Yuborishdan oldin kamida bitta JPEG, PNG yoki WebP rasmini tanlang.",
    "Bitta taqdimotda 3 tagacha fotosurat yuborishingiz mumkin.",
    "Suratga oling yoki tanlang",
    "rasmlar tanlangan",
    "Hech qanday surat tanlanmagan.",
    "Ko'rinadigan kod (ixtiyoriy)",
    "Nima xato ketdi? (ixtiyoriy)",
    "Bizning javobimiz uchun elektron pochta",
    "Faqat bu xabarga javob berish uchun foydalaniladi.",
    "Ruxsat talab qilinadi.",
    "Men bu mening fotosuratlarim ekanligini tasdiqlayman va Cosmetics Batch-ga fotosuratlar va mening elektron pochtamni saqlashga, ushbu taqdimnoma haqida men bilan bog‘lanishga va uning umumiy qo‘llanmalarini yaxshilash uchun tasdiqlangan fotosurat qismlaridan foydalanishga ruxsat beraman. Shaxsiy ma'lumotlar ko'rinmasligi kerak.",
    "Suratlarni yuborib bo‘lmadi. Kichikroq JPEG, PNG yoki WebP rasmlarni sinab ko'ring.",
    "Yuborilmoqda…",
    "Ko'rib chiqish uchun yuboring",
    "Kamera yoki galereyangizdan 3 tagacha JPEG, PNG yoki WebP tasvirni tanlang. Oʻrnatilgan joylashuv metamaʼlumotlarini olib tashlash uchun yuklashdan oldin har bir rasm hajmi oʻzgartiriladi va qayta kodlanadi. Maksimal: har bir qayta ishlangan tasvir uchun 5 MB. Yuzlar yoki boshqa shaxsiy maʼlumotlarni kiritishdan saqlaning."
  ],
  "az": [
    "BRANDNAME kodunu tapa və ya oxuya bilmirsiniz?",
    "Baza, etiket və ya qutunun aydın fotoşəkillərini göndərin. Biz onları nəzərdən keçirəcəyik və nümunələrimizi təkmilləşdirəcəyik.",
    "Kod şəkillərini göndərin",
    "Foto alındı",
    "Kodu nəzərdən keçirəcəyik və EMAILADDRESS ünvanına cavab verəcəyik.",
    "Göndərməzdən əvvəl ən azı bir JPEG, PNG və ya WebP şəkli seçin.",
    "Bir təqdimatda 3-ə qədər şəkil göndərə bilərsiniz.",
    "Şəkillər çəkin və ya seçin",
    "fotolar seçildi",
    "Heç bir şəkil seçilməyib.",
    "Görünən kod (isteğe bağlı)",
    "Nə səhv oldu? (isteğe bağlı)",
    "Cavabımız üçün e-poçt",
    "Yalnız bu təqdimata cavab vermək üçün istifadə olunur.",
    "İcazə tələb olunur.",
    "Mən təsdiq edirəm ki, bunlar mənim şəkillərimdir və Cosmetics Batch-ə şəkilləri və e-poçtumu saxlamağa, bu təqdimatla bağlı mənimlə əlaqə saxlamağa və ictimai bələdçilərini təkmilləşdirmək üçün təsdiqlənmiş foto hissələrdən istifadə etməyə icazə verirəm. Şəxsi məlumatlar görünməməlidir.",
    "Şəkilləri göndərmək mümkün olmadı. Daha kiçik JPEG, PNG və ya WebP şəkillərini sınayın.",
    "Göndərilir...",
    "Baxış üçün göndərin",
    "Kameranızdan və ya qalereyanızdan 3-ə qədər JPEG, PNG və ya WebP şəkli seçin. Daxil edilmiş məkan metadatasını silmək üçün yükləmədən əvvəl hər bir şəkil ölçüsü dəyişdirilir və yenidən kodlaşdırılır. Maksimum: hər işlənmiş şəkil üçün 5 MB. Üzləri və ya digər şəxsi məlumatları daxil etməkdən çəkinin."
  ],
  "kk": [
    "BRANDNAME кодын таба алмайсыз ба немесе оқи алмайсыз ба?",
    "Негіздің, жапсырманың немесе қораптың анық фотосуреттерін жіберіңіз. Біз оларды қарастырамыз және мысалдарымызды жетілдіреміз.",
    "Код фотосуреттерін жіберіңіз",
    "Фото алынды",
    "Біз кодты қарап шығып, EMAILADDRESS мекенжайына жауап береміз.",
    "Жібермес бұрын кем дегенде бір JPEG, PNG немесе WebP фотосуретін таңдаңыз.",
    "Бір өтініште 3 фотоға дейін жіберуге болады.",
    "Суретке түсіріңіз немесе таңдаңыз",
    "фотосуреттер таңдалды",
    "Ешбір фотосурет таңдалмаған.",
    "Көрінетін код (міндетті емес)",
    "Не болды? (міндетті емес)",
    "Біздің жауап үшін электрондық пошта",
    "Бұл жіберу туралы жауап беру үшін ғана пайдаланылады.",
    "Рұқсат қажет.",
    "Мен бұл менің фотосуреттерім екенін растаймын және Cosmetics Batch қолданбасына фотосуреттер мен электрондық поштамды сақтауға, осы жіберу туралы маған хабарласуға және оның жалпы нұсқаулықтарын жақсарту үшін расталған фотосурет бөліктерін пайдалануға рұқсат етемін. Жеке мәліметтер көрінбеуі керек.",
    "Фотосуреттерді жіберу мүмкін болмады. Кішірек JPEG, PNG немесе WebP кескіндерін қолданып көріңіз.",
    "Жіберілуде…",
    "Қарауға жіберу",
    "Камерадан немесе галереядан 3 JPEG, PNG немесе WebP кескініне дейін таңдаңыз. Енгізілген орын метадеректерін жою үшін жүктеп салу алдында әрбір сурет өлшемі өзгертіліп, қайта кодталады. Ең көбі: өңделген сурет үшін 5 МБ. Беттерді немесе басқа жеке мәліметтерді қоспаңыз."
  ]
};

/** Active locale inventory used by quality tests to prevent silent fallback. */
export const PHOTO_SUBMISSION_LOCALES = Object.freeze(Object.keys(RAW));

export function photoSubmissionCopy(locale: string): PhotoSubmissionCopy {
  const values = RAW[locale] ?? RAW.en;
  return Object.fromEntries(KEYS.map((key, index) => [key, values[index]])) as PhotoSubmissionCopy;
}
