export type ProductReferenceCopy = {
  title: string;
  body: string;
  expiry: string;
  batch: string;
  source: string;
};

const RAW: Record<string, ProductReferenceCopy> = {
  en: { title: "This is a product reference", body: "Reference {article} identifies {product}. It is not a batch code and contains no manufacture or expiry date.", expiry: "For shelf life, first use the EXP/expiry date printed elsewhere on the product or box.", batch: "If there is no printed expiry, enter the separate production batch code. Look for a shorter stamped, embossed or ink-printed code, or send a clear photo of every code area.", source: "Verify the product on Eucerin" },
  tr: { title: "Bu bir ürün referansıdır", body: "{article} referansı {product} ürününü tanımlar. Batch kodu değildir; üretim veya son kullanma tarihi içermez.", expiry: "Raf ömrü için önce ürünün veya kutunun başka bir yerinde yazan EXP/SKT tarihini kullanın.", batch: "Basılı SKT yoksa ayrı üretim batch kodunu girin. Daha kısa, damgalı, kabartmalı veya mürekkeple basılmış bir kod arayın ya da tüm kod alanlarının net fotoğrafını gönderin.", source: "Ürünü Eucerin'de doğrulayın" },
  de: { title: "Dies ist eine Produktreferenz", body: "Die Referenz {article} bezeichnet {product}. Sie ist kein Chargencode und enthält kein Herstellungs- oder Ablaufdatum.", expiry: "Verwenden Sie für die Haltbarkeit zuerst das an anderer Stelle auf Produkt oder Schachtel aufgedruckte EXP-/Ablaufdatum.", batch: "Wenn kein Ablaufdatum aufgedruckt ist, geben Sie den separaten Produktionschargencode ein. Suchen Sie nach einem kürzeren gestempelten, geprägten oder gedruckten Code oder senden Sie deutliche Fotos aller Codebereiche.", source: "Produkt bei Eucerin prüfen" },
  es: { title: "Esta es una referencia de producto", body: "La referencia {article} identifica {product}. No es un código de lote ni contiene una fecha de fabricación o caducidad.", expiry: "Para la vida útil, use primero la fecha EXP/caducidad impresa en otra parte del producto o la caja.", batch: "Si no hay fecha impresa, introduzca el código de lote de producción separado. Busque un código más corto, estampado, grabado o impreso, o envíe fotos claras de todas las zonas con códigos.", source: "Verificar el producto en Eucerin" },
  it: { title: "Questo è un riferimento prodotto", body: "Il riferimento {article} identifica {product}. Non è un codice di lotto e non contiene date di produzione o scadenza.", expiry: "Per la durata, utilizzare prima la data EXP/scadenza stampata altrove sul prodotto o sulla confezione.", batch: "Se non c'è una scadenza stampata, inserire il codice di lotto di produzione separato. Cercare un codice più breve, timbrato, inciso o stampato, oppure inviare foto nitide di tutte le aree con codici.", source: "Verifica il prodotto su Eucerin" },
  fr: { title: "Il s’agit d’une référence produit", body: "La référence {article} identifie {product}. Ce n’est pas un code de lot et elle ne contient aucune date de fabrication ou d’expiration.", expiry: "Pour la durée de conservation, utilisez d’abord la date EXP/péremption imprimée ailleurs sur le produit ou la boîte.", batch: "S’il n’y a pas de date imprimée, saisissez le code de lot de production distinct. Cherchez un code plus court tamponné, gravé ou imprimé, ou envoyez des photos nettes de toutes les zones de code.", source: "Vérifier le produit sur Eucerin" },
  nl: { title: "Dit is een productreferentie", body: "Referentie {article} identificeert {product}. Het is geen batchcode en bevat geen productie- of vervaldatum.", expiry: "Gebruik voor de houdbaarheid eerst de EXP-/vervaldatum die elders op het product of doosje staat.", batch: "Als er geen vervaldatum staat, voer dan de afzonderlijke productiebatchcode in. Zoek een kortere gestempelde, ingeperste of gedrukte code, of stuur duidelijke foto's van alle codeplekken.", source: "Product bij Eucerin controleren" },
  sv: { title: "Detta är en produktreferens", body: "Referens {article} identifierar {product}. Den är inte en batchkod och innehåller inget tillverknings- eller utgångsdatum.", expiry: "Använd först EXP-/utgångsdatumet som är tryckt någon annanstans på produkten eller kartongen.", batch: "Om inget datum finns, ange den separata produktionsbatchkoden. Leta efter en kortare stämplad, präglad eller tryckt kod, eller skicka tydliga foton av alla kodområden.", source: "Kontrollera produkten hos Eucerin" },
  da: { title: "Dette er en produktreference", body: "Reference {article} identificerer {product}. Det er ikke en batchkode og indeholder ingen produktions- eller udløbsdato.", expiry: "Brug først EXP-/udløbsdatoen, der er trykt et andet sted på produktet eller æsken.", batch: "Hvis der ikke er en trykt dato, skal du indtaste den separate produktionsbatchkode. Se efter en kortere stemplet, præget eller trykt kode, eller send tydelige fotos af alle kodeområder.", source: "Kontrollér produktet hos Eucerin" },
  pt: { title: "Esta é uma referência de produto", body: "A referência {article} identifica {product}. Não é um código de lote e não contém data de fabrico ou validade.", expiry: "Para a validade, use primeiro a data EXP/validade impressa noutro local do produto ou da caixa.", batch: "Se não houver data impressa, introduza o código de lote de produção separado. Procure um código mais curto, estampado, gravado ou impresso, ou envie fotografias nítidas de todas as áreas com códigos.", source: "Verificar o produto na Eucerin" },
  pl: { title: "To jest numer referencyjny produktu", body: "Numer {article} identyfikuje {product}. Nie jest kodem partii i nie zawiera daty produkcji ani ważności.", expiry: "Najpierw użyj daty EXP/ważności wydrukowanej w innym miejscu na produkcie lub pudełku.", batch: "Jeśli nie ma wydrukowanej daty, wpisz osobny kod partii produkcyjnej. Szukaj krótszego kodu stemplowanego, tłoczonego lub drukowanego albo prześlij wyraźne zdjęcia wszystkich miejsc z kodami.", source: "Sprawdź produkt w Eucerin" },
  ru: { title: "Это артикул продукта", body: "Артикул {article} обозначает {product}. Это не код партии, и он не содержит дату производства или срок годности.", expiry: "Сначала используйте дату EXP/срок годности, напечатанную в другом месте на продукте или коробке.", batch: "Если дата не напечатана, введите отдельный производственный код партии. Ищите более короткий штампованный, тиснёный или напечатанный код либо отправьте чёткие фотографии всех участков с кодами.", source: "Проверить продукт на сайте Eucerin" },
  ar: { title: "هذا رقم مرجعي للمنتج", body: "المرجع {article} يعرّف المنتج {product}. وهو ليس رمز تشغيلة ولا يحتوي على تاريخ إنتاج أو انتهاء.", expiry: "لمعرفة الصلاحية، استخدم أولًا تاريخ EXP/الانتهاء المطبوع في موضع آخر على المنتج أو العلبة.", batch: "إذا لم يوجد تاريخ مطبوع، فأدخل رمز تشغيلة الإنتاج المنفصل. ابحث عن رمز أقصر مختوم أو بارز أو مطبوع بالحبر، أو أرسل صورًا واضحة لجميع مواضع الرموز.", source: "تحقق من المنتج لدى Eucerin" },
  ja: { title: "これは製品参照番号です", body: "参照番号 {article} は {product} を示します。バッチコードではなく、製造日や使用期限の情報は含まれていません。", expiry: "使用期限については、まず製品または箱の別の場所に印字された EXP／使用期限を確認してください。", batch: "期限表示がない場合は、別の製造バッチコードを入力してください。より短いスタンプ、刻印、インク印字のコードを探すか、コードがあるすべての場所の鮮明な写真を送ってください。", source: "Eucerin で製品を確認" },
  ko: { title: "제품 참조 번호입니다", body: "참조 번호 {article}은(는) {product} 제품을 식별합니다. 배치 코드가 아니며 제조일이나 사용기한 정보가 들어 있지 않습니다.", expiry: "사용기한은 제품이나 상자의 다른 곳에 인쇄된 EXP/사용기한을 먼저 확인하세요.", batch: "인쇄된 기한이 없다면 별도의 생산 배치 코드를 입력하세요. 더 짧게 찍히거나 음각·양각 또는 잉크로 인쇄된 코드를 찾거나 모든 코드 위치의 선명한 사진을 보내주세요.", source: "Eucerin에서 제품 확인" },
  vi: { title: "Đây là mã tham chiếu sản phẩm", body: "Mã {article} xác định sản phẩm {product}. Đây không phải mã lô và không chứa ngày sản xuất hay hạn sử dụng.", expiry: "Trước tiên hãy dùng ngày EXP/hạn sử dụng được in ở vị trí khác trên sản phẩm hoặc hộp.", batch: "Nếu không có hạn sử dụng in sẵn, hãy nhập mã lô sản xuất riêng. Tìm mã ngắn hơn được đóng dấu, dập nổi hoặc in mực, hoặc gửi ảnh rõ tất cả vị trí có mã.", source: "Xác minh sản phẩm trên Eucerin" },
  id: { title: "Ini adalah referensi produk", body: "Referensi {article} mengidentifikasi {product}. Ini bukan kode batch dan tidak memuat tanggal produksi atau kedaluwarsa.", expiry: "Untuk masa simpan, gunakan dahulu tanggal EXP/kedaluwarsa yang dicetak di bagian lain produk atau kotak.", batch: "Jika tidak ada tanggal tercetak, masukkan kode batch produksi yang terpisah. Cari kode yang lebih pendek dan dicap, ditimbulkan, atau dicetak tinta, atau kirim foto jelas semua area kode.", source: "Verifikasi produk di Eucerin" },
  zh: { title: "这是产品参考编号", body: "参考编号 {article} 对应 {product}。它不是批号，也不包含生产日期或有效期。", expiry: "要查看有效期，请先使用产品或包装盒其他位置印有的 EXP／有效期日期。", batch: "如果没有印刷有效期，请输入单独的生产批号。寻找较短的盖印、压印或油墨印刷代码，或发送所有代码位置的清晰照片。", source: "在 Eucerin 核对产品" },
  yue: { title: "呢個係產品參考編號", body: "參考編號 {article} 對應 {product}。佢唔係批次碼，亦唔包含生產日期或有效期。", expiry: "要睇有效期，請先用產品或包裝盒其他位置印有嘅 EXP／有效期日期。", batch: "如果冇印上有效期，請輸入另一個生產批次碼。搵較短嘅蓋印、壓印或油墨印刷代碼，或者傳送所有代碼位置嘅清晰相片。", source: "喺 Eucerin 核對產品" },
};

export function productReferenceCopy(locale: string) {
  return RAW[locale] ?? RAW.en;
}

export const PRODUCT_REFERENCE_LOCALES = Object.freeze(Object.keys(RAW));
