#!/usr/bin/env node
/**
 * One-shot seed of hand-translated, high-visibility UI chrome for the initial
 * active locales, merged over the English base files. Long-form SEO content
 * (brandFaq, decoderExplain, storageTip, homeFaq, brand paragraphs) is left to
 * the machine pipeline (scripts/translate.mjs) and falls back to English until
 * then. Re-runnable and idempotent.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const MSG = join(dirname(fileURLToPath(import.meta.url)), "..", "messages");

/** dotted-key overrides per locale */
const T = {
  es: {
    "nav.home": "Inicio", "nav.brands": "Marcas", "nav.guides": "Guías",
    "nav.howItWorks": "Cómo funciona", "nav.about": "Acerca de", "nav.search": "Buscar",
    "nav.checkNow": "Comprobar", "nav.language": "Idioma",
    "hero.badge": "La confianza de amantes de la belleza en todo el mundo",
    "hero.title": "Comprueba los códigos de lote de cosméticos y perfumes",
    "hero.subtitle": "Descubre la fecha de fabricación, la antigüedad y la caducidad de tus cosméticos en segundos: gratis, al instante y privado.",
    "hero.trustFree": "100 % gratis", "hero.trustNoSignup": "Sin registro",
    "hero.trustPrivate": "Privado y seguro",
    "home.faqSubtitle": "Todo lo que necesitas saber para descifrar códigos de lote de cosméticos y perfumes.",
    "footer.tagline": "La forma más fiable y sencilla de comprobar códigos de lote de cosméticos y perfumes. Gratis, al instante y privado.",
    "footer.company": "Empresa", "footer.resources": "Recursos", "footer.aboutUs": "Sobre nosotros",
    "footer.howItWorks": "Cómo funciona", "footer.privacy": "Política de privacidad",
    "footer.terms": "Términos del servicio", "footer.batchGuide": "Guía de códigos de lote",
    "footer.shelfGuide": "Guía de caducidad", "footer.allBrands": "Todas las marcas",
    "footer.allGuides": "Todas las guías",
    "footer.rights": "© {year} {name}. Todos los derechos reservados. Las estimaciones son solo informativas y no garantizan la seguridad del producto.",
    "faqUi.title": "Preguntas frecuentes", "faqUi.showMore": "Mostrar {n} preguntas más",
    "faqUi.showFewer": "Mostrar menos preguntas",
    "categoryNoun.skincare": "cuidado de la piel", "categoryNoun.makeup": "maquillaje",
    "categoryNoun.perfume": "fragancia", "categoryNoun.haircare": "cuidado del cabello",
    "categoryNoun.suncare": "protección solar", "categoryNoun.generic": "belleza",
    "brandPage.by": "de {group}", "brandPage.checkerTitle": "Verificador de código de lote de {name}",
    "brandPage.intro": "Introduce el código de lote de {name} abajo para descifrar al instante la fecha de fabricación, la antigüedad y la caducidad estimada: gratis y privado.",
    "brandPage.howHeading": "Cómo funcionan los códigos de lote de {name}",
    "brandPage.workedExampleTitle": "Ejemplo práctico", "brandPage.factManufacturer": "Fabricante",
    "brandPage.factShelfLife": "Vida útil típica", "brandPage.factPao": "Tras abrir (PAO)",
    "brandPage.factDecoder": "Decodificador", "brandPage.autoDecoder": "Detección automática de fecha",
    "brandPage.months": "{n} meses", "brandPage.relatedBrands": "Marcas relacionadas",
    "brandPage.helpfulGuides": "Guías útiles", "brandPage.faqTitle": "{name} — Preguntas frecuentes",
  },
  fr: {
    "nav.home": "Accueil", "nav.brands": "Marques", "nav.guides": "Guides",
    "nav.howItWorks": "Comment ça marche", "nav.about": "À propos", "nav.search": "Rechercher",
    "nav.checkNow": "Vérifier", "nav.language": "Langue",
    "hero.badge": "La référence des passionnés de beauté dans le monde entier",
    "hero.title": "Vérifiez les codes de lot des cosmétiques et parfums",
    "hero.subtitle": "Trouvez la date de fabrication, l’âge et la date de péremption de vos cosmétiques en quelques secondes — gratuit, instantané et privé.",
    "hero.trustFree": "100 % gratuit", "hero.trustNoSignup": "Sans inscription",
    "hero.trustPrivate": "Privé et sécurisé",
    "home.faqSubtitle": "Tout ce qu’il faut savoir pour décoder les codes de lot des cosmétiques et parfums.",
    "footer.tagline": "Le moyen le plus fiable et le plus simple de vérifier les codes de lot des cosmétiques et parfums. Gratuit, instantané et privé.",
    "footer.company": "Entreprise", "footer.resources": "Ressources", "footer.aboutUs": "À propos",
    "footer.howItWorks": "Comment ça marche", "footer.privacy": "Politique de confidentialité",
    "footer.terms": "Conditions d’utilisation", "footer.batchGuide": "Guide des codes de lot",
    "footer.shelfGuide": "Guide de conservation", "footer.allBrands": "Toutes les marques",
    "footer.allGuides": "Tous les guides",
    "footer.rights": "© {year} {name}. Tous droits réservés. Les estimations sont fournies à titre indicatif et ne garantissent pas la sécurité du produit.",
    "faqUi.title": "Questions fréquentes", "faqUi.showMore": "Afficher {n} questions de plus",
    "faqUi.showFewer": "Afficher moins de questions",
    "categoryNoun.skincare": "soin de la peau", "categoryNoun.makeup": "maquillage",
    "categoryNoun.perfume": "parfum", "categoryNoun.haircare": "soin capillaire",
    "categoryNoun.suncare": "protection solaire", "categoryNoun.generic": "beauté",
    "brandPage.by": "par {group}", "brandPage.checkerTitle": "Vérificateur de code de lot {name}",
    "brandPage.intro": "Saisissez votre code de lot {name} ci-dessous pour décoder instantanément la date de fabrication, l’âge et la date de péremption estimée — gratuit et privé.",
    "brandPage.howHeading": "Comment fonctionnent les codes de lot {name}",
    "brandPage.workedExampleTitle": "Exemple concret", "brandPage.factManufacturer": "Fabricant",
    "brandPage.factShelfLife": "Durée de conservation typique", "brandPage.factPao": "Après ouverture (PAO)",
    "brandPage.factDecoder": "Décodeur", "brandPage.autoDecoder": "Détection automatique de la date",
    "brandPage.months": "{n} mois", "brandPage.relatedBrands": "Marques associées",
    "brandPage.helpfulGuides": "Guides utiles", "brandPage.faqTitle": "{name} — FAQ",
  },
  de: {
    "nav.home": "Start", "nav.brands": "Marken", "nav.guides": "Ratgeber",
    "nav.howItWorks": "So funktioniert’s", "nav.about": "Über uns", "nav.search": "Suchen",
    "nav.checkNow": "Prüfen", "nav.language": "Sprache",
    "hero.badge": "Weltweit von Beauty-Fans genutzt",
    "hero.title": "Chargencodes von Kosmetik & Parfüm prüfen",
    "hero.subtitle": "Finde Herstellungsdatum, Alter und Haltbarkeit deiner Kosmetik in Sekunden – kostenlos, sofort und privat.",
    "hero.trustFree": "100 % kostenlos", "hero.trustNoSignup": "Keine Anmeldung",
    "hero.trustPrivate": "Privat & sicher",
    "home.faqSubtitle": "Alles Wissenswerte zum Entschlüsseln von Chargencodes bei Kosmetik und Parfüm.",
    "footer.tagline": "Der vertrauenswürdigste und einfachste Weg, Chargencodes von Kosmetik & Parfüm zu prüfen. Kostenlos, sofort und privat.",
    "footer.company": "Unternehmen", "footer.resources": "Ressourcen", "footer.aboutUs": "Über uns",
    "footer.howItWorks": "So funktioniert’s", "footer.privacy": "Datenschutz",
    "footer.terms": "Nutzungsbedingungen", "footer.batchGuide": "Chargencode-Ratgeber",
    "footer.shelfGuide": "Haltbarkeits-Ratgeber", "footer.allBrands": "Alle Marken",
    "footer.allGuides": "Alle Ratgeber",
    "footer.rights": "© {year} {name}. Alle Rechte vorbehalten. Schätzungen dienen nur zur Information und sind keine Garantie für die Produktsicherheit.",
    "faqUi.title": "Häufige Fragen", "faqUi.showMore": "{n} weitere Fragen anzeigen",
    "faqUi.showFewer": "Weniger Fragen anzeigen",
    "categoryNoun.skincare": "Hautpflege", "categoryNoun.makeup": "Make-up",
    "categoryNoun.perfume": "Duft", "categoryNoun.haircare": "Haarpflege",
    "categoryNoun.suncare": "Sonnenpflege", "categoryNoun.generic": "Beauty",
    "brandPage.by": "von {group}", "brandPage.checkerTitle": "{name} Chargencode-Prüfer",
    "brandPage.intro": "Gib unten deinen {name}-Chargencode ein, um Herstellungsdatum, Alter und geschätztes Haltbarkeitsdatum sofort zu entschlüsseln – kostenlos und privat.",
    "brandPage.howHeading": "So funktionieren {name}-Chargencodes",
    "brandPage.workedExampleTitle": "Beispiel", "brandPage.factManufacturer": "Hersteller",
    "brandPage.factShelfLife": "Typische Haltbarkeit", "brandPage.factPao": "Nach dem Öffnen (PAO)",
    "brandPage.factDecoder": "Decoder", "brandPage.autoDecoder": "Automatische Datumserkennung",
    "brandPage.months": "{n} Monate", "brandPage.relatedBrands": "Verwandte Marken",
    "brandPage.helpfulGuides": "Hilfreiche Ratgeber", "brandPage.faqTitle": "{name} – FAQ",
  },
  pt: {
    "nav.home": "Início", "nav.brands": "Marcas", "nav.guides": "Guias",
    "nav.howItWorks": "Como funciona", "nav.about": "Sobre", "nav.search": "Pesquisar",
    "nav.checkNow": "Verificar", "nav.language": "Idioma",
    "hero.badge": "A escolha de amantes da beleza em todo o mundo",
    "hero.title": "Verifique os códigos de lote de cosméticos e perfumes",
    "hero.subtitle": "Descubra a data de fabrico, a idade e a validade dos seus cosméticos em segundos — grátis, instantâneo e privado.",
    "hero.trustFree": "100% grátis", "hero.trustNoSignup": "Sem registo",
    "hero.trustPrivate": "Privado e seguro",
    "home.faqSubtitle": "Tudo o que precisa de saber para descodificar códigos de lote de cosméticos e perfumes.",
    "footer.tagline": "A forma mais fiável e simples de verificar códigos de lote de cosméticos e perfumes. Grátis, instantâneo e privado.",
    "footer.company": "Empresa", "footer.resources": "Recursos", "footer.aboutUs": "Sobre nós",
    "footer.howItWorks": "Como funciona", "footer.privacy": "Política de privacidade",
    "footer.terms": "Termos de serviço", "footer.batchGuide": "Guia de códigos de lote",
    "footer.shelfGuide": "Guia de validade", "footer.allBrands": "Todas as marcas",
    "footer.allGuides": "Todos os guias",
    "footer.rights": "© {year} {name}. Todos os direitos reservados. As estimativas são apenas informativas e não garantem a segurança do produto.",
    "faqUi.title": "Perguntas frequentes", "faqUi.showMore": "Mostrar mais {n} perguntas",
    "faqUi.showFewer": "Mostrar menos perguntas",
    "categoryNoun.skincare": "cuidados com a pele", "categoryNoun.makeup": "maquilhagem",
    "categoryNoun.perfume": "fragrância", "categoryNoun.haircare": "cuidados capilares",
    "categoryNoun.suncare": "proteção solar", "categoryNoun.generic": "beleza",
    "brandPage.by": "por {group}", "brandPage.checkerTitle": "Verificador de código de lote {name}",
    "brandPage.intro": "Introduza o código de lote {name} abaixo para descodificar instantaneamente a data de fabrico, a idade e a validade estimada — grátis e privado.",
    "brandPage.howHeading": "Como funcionam os códigos de lote {name}",
    "brandPage.workedExampleTitle": "Exemplo prático", "brandPage.factManufacturer": "Fabricante",
    "brandPage.factShelfLife": "Validade típica", "brandPage.factPao": "Após abertura (PAO)",
    "brandPage.factDecoder": "Descodificador", "brandPage.autoDecoder": "Deteção automática de data",
    "brandPage.months": "{n} meses", "brandPage.relatedBrands": "Marcas relacionadas",
    "brandPage.helpfulGuides": "Guias úteis", "brandPage.faqTitle": "{name} — FAQ",
  },
  ru: {
    "nav.home": "Главная", "nav.brands": "Бренды", "nav.guides": "Гиды",
    "nav.howItWorks": "Как это работает", "nav.about": "О нас", "nav.search": "Поиск",
    "nav.checkNow": "Проверить", "nav.language": "Язык",
    "hero.badge": "Нам доверяют любители красоты по всему миру",
    "hero.title": "Проверьте коды партий косметики и парфюмерии",
    "hero.subtitle": "Узнайте дату производства, возраст и срок годности вашей косметики за секунды — бесплатно, мгновенно и конфиденциально.",
    "hero.trustFree": "100% бесплатно", "hero.trustNoSignup": "Без регистрации",
    "hero.trustPrivate": "Конфиденциально и безопасно",
    "home.faqSubtitle": "Всё, что нужно знать о расшифровке кодов партий косметики и парфюмерии.",
    "footer.tagline": "Самый надёжный и простой способ проверить коды партий косметики и парфюмерии. Бесплатно, мгновенно и конфиденциально.",
    "footer.company": "Компания", "footer.resources": "Ресурсы", "footer.aboutUs": "О нас",
    "footer.howItWorks": "Как это работает", "footer.privacy": "Политика конфиденциальности",
    "footer.terms": "Условия использования", "footer.batchGuide": "Гид по кодам партий",
    "footer.shelfGuide": "Гид по срокам годности", "footer.allBrands": "Все бренды",
    "footer.allGuides": "Все гиды",
    "footer.rights": "© {year} {name}. Все права защищены. Оценки носят справочный характер и не гарантируют безопасность продукта.",
    "faqUi.title": "Частые вопросы", "faqUi.showMore": "Показать ещё {n} вопросов",
    "faqUi.showFewer": "Показать меньше вопросов",
    "categoryNoun.skincare": "уход за кожей", "categoryNoun.makeup": "макияж",
    "categoryNoun.perfume": "аромат", "categoryNoun.haircare": "уход за волосами",
    "categoryNoun.suncare": "солнцезащита", "categoryNoun.generic": "красота",
    "brandPage.by": "от {group}", "brandPage.checkerTitle": "Проверка кода партии {name}",
    "brandPage.intro": "Введите код партии {name} ниже, чтобы мгновенно расшифровать дату производства, возраст и предполагаемый срок годности — бесплатно и конфиденциально.",
    "brandPage.howHeading": "Как работают коды партий {name}",
    "brandPage.workedExampleTitle": "Пример", "brandPage.factManufacturer": "Производитель",
    "brandPage.factShelfLife": "Типичный срок годности", "brandPage.factPao": "После вскрытия (PAO)",
    "brandPage.factDecoder": "Декодер", "brandPage.autoDecoder": "Автоопределение даты",
    "brandPage.months": "{n} мес.", "brandPage.relatedBrands": "Похожие бренды",
    "brandPage.helpfulGuides": "Полезные гиды", "brandPage.faqTitle": "{name} — FAQ",
  },
  ar: {
    "nav.home": "الرئيسية", "nav.brands": "العلامات التجارية", "nav.guides": "الأدلة",
    "nav.howItWorks": "كيف يعمل", "nav.about": "من نحن", "nav.search": "بحث",
    "nav.checkNow": "تحقّق الآن", "nav.language": "اللغة",
    "hero.badge": "موثوق من محبي الجمال حول العالم",
    "hero.title": "تحقّق من رموز تشغيل مستحضرات التجميل والعطور",
    "hero.subtitle": "اعرف تاريخ التصنيع والعمر وتاريخ انتهاء الصلاحية لمستحضراتك في ثوانٍ — مجانًا وفوريًا وخاصًا.",
    "hero.trustFree": "مجاني 100٪", "hero.trustNoSignup": "بدون تسجيل",
    "hero.trustPrivate": "خاص وآمن",
    "home.faqSubtitle": "كل ما تحتاج معرفته لفك رموز تشغيل مستحضرات التجميل والعطور.",
    "footer.tagline": "أسهل وأوثق طريقة للتحقّق من رموز تشغيل مستحضرات التجميل والعطور. مجاني وفوري وخاص.",
    "footer.company": "الشركة", "footer.resources": "الموارد", "footer.aboutUs": "من نحن",
    "footer.howItWorks": "كيف يعمل", "footer.privacy": "سياسة الخصوصية",
    "footer.terms": "شروط الخدمة", "footer.batchGuide": "دليل رموز التشغيل",
    "footer.shelfGuide": "دليل مدة الصلاحية", "footer.allBrands": "كل العلامات التجارية",
    "footer.allGuides": "كل الأدلة",
    "footer.rights": "© {year} {name}. جميع الحقوق محفوظة. التقديرات لأغراض إعلامية فقط وليست ضمانًا لسلامة المنتج.",
    "faqUi.title": "الأسئلة الشائعة", "faqUi.showMore": "عرض {n} أسئلة إضافية",
    "faqUi.showFewer": "عرض أسئلة أقل",
    "categoryNoun.skincare": "العناية بالبشرة", "categoryNoun.makeup": "المكياج",
    "categoryNoun.perfume": "العطر", "categoryNoun.haircare": "العناية بالشعر",
    "categoryNoun.suncare": "الحماية من الشمس", "categoryNoun.generic": "الجمال",
    "brandPage.by": "من {group}", "brandPage.checkerTitle": "أداة فحص رمز تشغيل {name}",
    "brandPage.intro": "أدخل رمز تشغيل {name} أدناه لفك تاريخ التصنيع والعمر وتاريخ انتهاء الصلاحية المقدَّر فورًا — مجانًا وبخصوصية.",
    "brandPage.howHeading": "كيف تعمل رموز تشغيل {name}",
    "brandPage.workedExampleTitle": "مثال تطبيقي", "brandPage.factManufacturer": "الشركة المصنِّعة",
    "brandPage.factShelfLife": "مدة الصلاحية المعتادة", "brandPage.factPao": "بعد الفتح (PAO)",
    "brandPage.factDecoder": "أداة الفك", "brandPage.autoDecoder": "كشف التاريخ تلقائيًا",
    "brandPage.months": "{n} شهرًا", "brandPage.relatedBrands": "علامات ذات صلة",
    "brandPage.helpfulGuides": "أدلة مفيدة", "brandPage.faqTitle": "{name} — الأسئلة الشائعة",
  },
  zh: {
    "nav.home": "首页", "nav.brands": "品牌", "nav.guides": "指南",
    "nav.howItWorks": "工作原理", "nav.about": "关于", "nav.search": "搜索",
    "nav.checkNow": "立即查询", "nav.language": "语言",
    "hero.badge": "全球美妆爱好者的信赖之选",
    "hero.title": "查询化妆品和香水的批号",
    "hero.subtitle": "几秒钟即可查出化妆品的生产日期、使用时长和保质期——免费、即时、私密。",
    "hero.trustFree": "100% 免费", "hero.trustNoSignup": "无需注册",
    "hero.trustPrivate": "私密且安全",
    "home.faqSubtitle": "解读化妆品和香水批号所需了解的一切。",
    "footer.tagline": "查询化妆品和香水批号最可靠、最简单的方式。免费、即时、私密。",
    "footer.company": "公司", "footer.resources": "资源", "footer.aboutUs": "关于我们",
    "footer.howItWorks": "工作原理", "footer.privacy": "隐私政策",
    "footer.terms": "服务条款", "footer.batchGuide": "批号指南",
    "footer.shelfGuide": "保质期指南", "footer.allBrands": "所有品牌",
    "footer.allGuides": "所有指南",
    "footer.rights": "© {year} {name}。保留所有权利。估算结果仅供参考，不构成对产品安全的保证。",
    "faqUi.title": "常见问题", "faqUi.showMore": "再显示 {n} 个问题",
    "faqUi.showFewer": "收起问题",
    "categoryNoun.skincare": "护肤品", "categoryNoun.makeup": "彩妆",
    "categoryNoun.perfume": "香水", "categoryNoun.haircare": "护发",
    "categoryNoun.suncare": "防晒", "categoryNoun.generic": "美妆",
    "brandPage.by": "由 {group} 生产", "brandPage.checkerTitle": "{name} 批号查询器",
    "brandPage.intro": "在下方输入你的 {name} 批号，立即解读生产日期、使用时长和预计保质期——免费且私密。",
    "brandPage.howHeading": "{name} 批号的工作原理",
    "brandPage.workedExampleTitle": "示例", "brandPage.factManufacturer": "生产商",
    "brandPage.factShelfLife": "典型保质期", "brandPage.factPao": "开封后（PAO）",
    "brandPage.factDecoder": "解码器", "brandPage.autoDecoder": "自动日期识别",
    "brandPage.months": "{n} 个月", "brandPage.relatedBrands": "相关品牌",
    "brandPage.helpfulGuides": "实用指南", "brandPage.faqTitle": "{name} — 常见问题",
  },
};

function setDeep(obj, dotted, value) {
  const parts = dotted.split(".");
  let cur = obj;
  for (let i = 0; i < parts.length - 1; i++) cur = cur[parts[i]] ??= {};
  cur[parts[parts.length - 1]] = value;
}

for (const [code, overrides] of Object.entries(T)) {
  const path = join(MSG, `${code}.json`);
  const dict = JSON.parse(readFileSync(path, "utf8"));
  for (const [key, val] of Object.entries(overrides)) setDeep(dict, key, val);
  writeFileSync(path, JSON.stringify(dict, null, 2) + "\n");
  console.log(`seeded ${code}: ${Object.keys(overrides).length} keys`);
}
